// -------------------------------------------------------------
// 
// File Name: hdlsrc/hdl_generation_2/Discrete_PID_Controller.sv
// Created: 2025-11-01 20:39:50
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


import hdl_generation_2_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Discrete_PID_Controller
// Source Path: hdl_generation_2/Discrete PID Controller
// Hierarchy Level: 1
// Model version: 1.34
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Discrete_PID_Controller
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] u[0:2]  /* single [3] */,
             output logic [31:0] y[0:2]  /* single [3] */);


  logic [31:0] kconst;  /* ufix32 */
  logic [31:0] Filter_x_reg [0:2];  /* ufix32 [3] */
  logic [31:0] nfp_out_3_1;  /* ufix32 */
  logic [31:0] nfp_out_3_1_1;  /* ufix32 */
  logic [31:0] nfp_out_3_1_2;  /* ufix32 */
  logic [31:0] nfp_out_2_1;  /* ufix32 */
  logic [31:0] nfp_out_2_1_1;  /* ufix32 */
  logic [31:0] nfp_out_2_1_2;  /* ufix32 */
  logic [31:0] nfp_out_1_1;  /* ufix32 */
  logic [31:0] nfp_out_1_1_1;  /* ufix32 */
  logic [31:0] nfp_out_1_1_2;  /* ufix32 */
  logic [31:0] Filter_u_add [0:2];  /* ufix32 [3] */
  logic [31:0] nfp_out_1_1_3;  /* ufix32 */
  logic [31:0] nfp_out_2_1_3;  /* ufix32 */
  logic [31:0] nfp_out_3_1_3;  /* ufix32 */
  logic [31:0] Sum_out1 [0:2];  /* ufix32 [3] */

  // Feedback Features
  // Derivative
  // Integrator


  assign kconst = 32'h3a83126f;

  nfp_sub_single u_nfp_sub_comp (.nfp_in1(u[2]),  /* single */
                                 .nfp_in2(Filter_x_reg[2]),  /* single */
                                 .nfp_out(nfp_out_3_1)  /* single */
                                 );
  nfp_mul_single u_nfp_mul_comp (.nfp_in1(nfp_out_3_1),  /* single */
                                 .nfp_in2(kconst),  /* single */
                                 .nfp_out(nfp_out_3_1_1)  /* single */
                                 );

  nfp_add_single u_nfp_add_comp (.nfp_in1(Filter_x_reg[2]),  /* single */
                                 .nfp_in2(nfp_out_3_1_1),  /* single */
                                 .nfp_out(nfp_out_3_1_2)  /* single */
                                 );

  nfp_sub_single u_nfp_sub_comp_1 (.nfp_in1(u[1]),  /* single */
                                   .nfp_in2(Filter_x_reg[1]),  /* single */
                                   .nfp_out(nfp_out_2_1)  /* single */
                                   );

  nfp_mul_single u_nfp_mul_comp_1 (.nfp_in1(nfp_out_2_1),  /* single */
                                   .nfp_in2(kconst),  /* single */
                                   .nfp_out(nfp_out_2_1_1)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_1 (.nfp_in1(Filter_x_reg[1]),  /* single */
                                   .nfp_in2(nfp_out_2_1_1),  /* single */
                                   .nfp_out(nfp_out_2_1_2)  /* single */
                                   );

  nfp_mul_single u_nfp_mul_comp_2 (.nfp_in1(nfp_out_1_1),  /* single */
                                   .nfp_in2(kconst),  /* single */
                                   .nfp_out(nfp_out_1_1_1)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_2 (.nfp_in1(Filter_x_reg[0]),  /* single */
                                   .nfp_in2(nfp_out_1_1_1),  /* single */
                                   .nfp_out(nfp_out_1_1_2)  /* single */
                                   );

  assign Filter_u_add[0] = nfp_out_1_1_2;
  assign Filter_u_add[1] = nfp_out_2_1_2;
  assign Filter_u_add[2] = nfp_out_3_1_2;
  always_ff @(posedge clk or posedge reset)
    begin : Filter_reg_process
      if (reset == 1'b1) begin
        Filter_x_reg <= '{3{32'h00000000}};
      end
      else begin
        if (enb) begin
          Filter_x_reg <= Filter_u_add;
        end
      end
    end
  nfp_sub_single u_nfp_sub_comp_2 (.nfp_in1(u[0]),  /* single */
                                   .nfp_in2(Filter_x_reg[0]),  /* single */
                                   .nfp_out(nfp_out_1_1)  /* single */
                                   );
  nfp_add_single u_nfp_add_comp_3 (.nfp_in1(u[0]),  /* single */
                                   .nfp_in2(nfp_out_1_1),  /* single */
                                   .nfp_out(nfp_out_1_1_3)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_4 (.nfp_in1(u[1]),  /* single */
                                   .nfp_in2(nfp_out_2_1),  /* single */
                                   .nfp_out(nfp_out_2_1_3)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_5 (.nfp_in1(u[2]),  /* single */
                                   .nfp_in2(nfp_out_3_1),  /* single */
                                   .nfp_out(nfp_out_3_1_3)  /* single */
                                   );

  assign Sum_out1[0] = nfp_out_1_1_3;
  assign Sum_out1[1] = nfp_out_2_1_3;
  assign Sum_out1[2] = nfp_out_3_1_3;

  assign y = Sum_out1;

endmodule  // Discrete_PID_Controller

