// -------------------------------------------------------------
// 
// File Name: hdlsrc/hdl_generation_2/hdl_generation_2.sv
// Created: 2025-11-01 20:39:50
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.001
// Target subsystem base rate: 0.001
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.001
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// servo_x                       ce_out        0.001
// servo_y                       ce_out        0.001
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


import hdl_generation_2_pkg::* ;

// -------------------------------------------------------------
// 
// Module: hdl_generation_2
// Source Path: hdl_generation_2
// Hierarchy Level: 0
// Model version: 1.34
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module hdl_generation_2
          (  input logic clk,
             input logic reset,
             input logic clk_enable,
             input logic [31:0] q_des[0:3]  /* single [4] */,
             input logic [31:0] q[0:3]  /* single [4] */,
             input logic [31:0] Inertia  /* single */,
             input logic [31:0] Angular_Velocity[0:2]  /* single [3] */,
             input logic [31:0] r_gim[0:2]  /* single [3] */,
             input logic [31:0] norm_t  /* single */,
             output logic ce_out,
             output logic [31:0] servo_x  /* single */,
             output logic [31:0] servo_y  /* single */);


  logic enb;
  logic [31:0] nfp_out_1_1;  /* ufix32 */
  logic [31:0] nfp_out_2_1;  /* ufix32 */
  logic [31:0] nfp_out_3_1;  /* ufix32 */
  logic [31:0] nfp_out_4_1;  /* ufix32 */
  logic [31:0] Sum3_out1 [0:3];  /* ufix32 [4] */
  logic [31:0] Unit_Delay5_out1 [0:3];  /* ufix32 [4] */
  logic [31:0] v;  /* ufix32 */
  logic [31:0] out1;  /* ufix32 */
  logic [31:0] norm_v;  /* ufix32 */
  logic [31:0] q_0;  /* ufix32 */
  logic [31:0] nfp_out_1_1_1;  /* ufix32 */
  logic pw2_sign_const;  /* ufix1 */
  logic signed [8:0] pw2_shift_const;  /* sfix9 */
  logic [31:0] nfp_out_1_1_2;  /* ufix32 */
  logic [31:0] nfp_out_1_1_3;  /* ufix32 */
  logic [31:0] nfp_out_1_1_4;  /* ufix32 */
  logic [31:0] nfp_out_1_1_5;  /* ufix32 */
  logic [31:0] nfp_out_2_1_1;  /* ufix32 */
  logic pw2_sign_const_1;  /* ufix1 */
  logic signed [8:0] pw2_shift_const_1;  /* sfix9 */
  logic [31:0] nfp_out_2_1_2;  /* ufix32 */
  logic [31:0] nfp_out_2_1_3;  /* ufix32 */
  logic [31:0] nfp_out_2_1_4;  /* ufix32 */
  logic [31:0] nfp_out_2_1_5;  /* ufix32 */
  logic [31:0] nfp_out_3_1_1;  /* ufix32 */
  logic pw2_sign_const_2;  /* ufix1 */
  logic signed [8:0] pw2_shift_const_2;  /* sfix9 */
  logic [31:0] nfp_out_3_1_2;  /* ufix32 */
  logic [31:0] nfp_out_3_1_3;  /* ufix32 */
  logic [31:0] nfp_out_3_1_4;  /* ufix32 */
  logic [31:0] nfp_out_3_1_5;  /* ufix32 */
  logic [31:0] psi [0:2];  /* ufix32 [3] */
  logic [31:0] Unit_Delay6_out1 [0:2];  /* ufix32 [3] */
  logic [31:0] Discrete_PID_Controller_out1 [0:2];  /* ufix32 [3] */
  logic [31:0] nfp_out_1_1_6;  /* ufix32 */
  logic [31:0] nfp_out_2_1_6;  /* ufix32 */
  logic [31:0] nfp_out_3_1_6;  /* ufix32 */
  logic [31:0] nfp_out_1_1_7;  /* ufix32 */
  logic [31:0] nfp_out_2_1_7;  /* ufix32 */
  logic [31:0] nfp_out_3_1_7;  /* ufix32 */
  logic [31:0] tau_gyro [0:2];  /* ufix32 [3] */
  logic [31:0] Unit_Delay7_out1 [0:2];  /* ufix32 [3] */
  logic [31:0] nfp_out_1_1_8;  /* ufix32 */
  logic [31:0] nfp_out_1_1_9;  /* ufix32 */
  logic [31:0] nfp_out_3_1_8;  /* ufix32 */
  logic [31:0] nfp_out_3_1_9;  /* ufix32 */
  logic Unit_Delay_ctrl_const_out;
  logic Unit_Delay_ctrl_delay_out;
  logic [31:0] Unit_Delay_Initial_Val_out [0:2];  /* ufix32 [3] */
  logic [31:0] Unit_Delay_out [0:2];  /* ufix32 [3] */
  logic [31:0] Unit_Delay_out1 [0:2];  /* ufix32 [3] */
  logic [31:0] tmp_Dot_Product1_dotp_2;  /* ufix32 */
  logic [31:0] tmp_Dot_Product1_dotp_1;  /* ufix32 */
  logic [31:0] tmp_Dot_Product1_dotp_0;  /* ufix32 */
  logic [31:0] sum_Dot_Product1_dotp_1;  /* ufix32 */
  logic [31:0] out1_1;  /* ufix32 */
  logic [31:0] Unit_Delay2_out1;  /* ufix32 */
  logic [31:0] Sqrt_out1;  /* ufix32 */
  logic [31:0] Upperlimit_out;  /* ufix32 */
  logic [31:0] Lowerlimit_out;  /* ufix32 */
  logic [31:0] nfp_out_2_1_8;  /* ufix32 */
  logic [31:0] nfp_out_2_1_9;  /* ufix32 */
  logic [31:0] Upperlimit_out_1;  /* ufix32 */
  logic [31:0] Lowerlimit_out_1;  /* ufix32 */
  logic [31:0] Upperlimit_out_2;  /* ufix32 */
  logic [31:0] Lowerlimit_out_2;  /* ufix32 */
  logic [31:0] theta_x;  /* ufix32 */
  logic UpperRelop_out;
  logic [31:0] Switch1_out;  /* ufix32 */
  logic [31:0] nfp_out_2_1_10;  /* ufix32 */
  logic [31:0] Sqrt2_out1;  /* ufix32 */
  logic [31:0] nfp_out_2_1_11;  /* ufix32 */
  logic [31:0] Unit_Delay3_out1 [0:2];  /* ufix32 [3] */
  logic [31:0] Saturation_out1;  /* ufix32 */
  logic [31:0] Product5_out1;  /* ufix32 */
  logic [31:0] nfp_out_3_1_10;  /* ufix32 */
  logic [31:0] nfp_out_3_1_11;  /* ufix32 */
  logic [31:0] nfp_out_3_1_12;  /* ufix32 */
  logic [31:0] nfp_out_3_1_13;  /* ufix32 */
  logic [31:0] Gain3_out1;  /* ufix32 */
  logic [31:0] nfp_out_2_1_12;  /* ufix32 */
  logic [31:0] nfp_out_2_1_13;  /* ufix32 */
  logic [31:0] nfp_out_2_1_14;  /* ufix32 */
  logic [31:0] nfp_out_2_1_15;  /* ufix32 */
  logic [31:0] out1_2;  /* ufix32 */
  logic UpperRelop_out_1;
  logic [31:0] Switch1_out_1;  /* ufix32 */
  logic [31:0] Sin_out1;  /* ufix32 */
  logic [31:0] tmp_Dot_Product_dotp_0;  /* ufix32 */
  logic [31:0] Sin1_out1;  /* ufix32 */
  logic [31:0] Cos_out1;  /* ufix32 */
  logic [31:0] Product4_out1;  /* ufix32 */
  logic [31:0] tmp_Dot_Product_dotp_1;  /* ufix32 */
  logic [31:0] sum_Dot_Product_dotp_1;  /* ufix32 */
  logic [31:0] theta_y;  /* ufix32 */
  logic UpperRelop_out_2;
  logic [31:0] Switch1_out_2;  /* ufix32 */
  logic [31:0] nfp_out_1_1_10;  /* ufix32 */
  logic [31:0] tmp_Dot_Product3_dotp_0;  /* ufix32 */
  logic [31:0] Unit_Delay1_out1 [0:2];  /* ufix32 [3] */
  logic [31:0] tmp_Dot_Product3_dotp_1;  /* ufix32 */
  logic [31:0] sum_Dot_Product3_dotp_1;  /* ufix32 */
  logic [31:0] nfp_out_3_1_14;  /* ufix32 */
  logic [31:0] tmp_Dot_Product3_dotp_2;  /* ufix32 */
  logic [31:0] out1_3;  /* ufix32 */
  logic [31:0] Subtract_out1;  /* ufix32 */
  logic [31:0] nfp_out_3_1_15;  /* ufix32 */
  logic [31:0] nfp_out_3_1_16;  /* ufix32 */
  logic [31:0] nfp_out_3_1_17;  /* ufix32 */
  logic [31:0] nfp_out_2_1_16;  /* ufix32 */
  logic [31:0] nfp_out_2_1_17;  /* ufix32 */
  logic [31:0] nfp_out_2_1_18;  /* ufix32 */
  logic [31:0] tmp_Dot_Product2_dotp_0;  /* ufix32 */
  logic [31:0] tmp_Dot_Product2_dotp_1;  /* ufix32 */
  logic [31:0] sum_Dot_Product2_dotp_1;  /* ufix32 */
  logic [31:0] tmp_Dot_Product2_dotp_2;  /* ufix32 */
  logic [31:0] out1_4;  /* ufix32 */
  logic [31:0] nfp_out_1_1_11;  /* ufix32 */
  logic [31:0] nfp_out_1_1_12;  /* ufix32 */
  logic [31:0] nfp_out_1_1_13;  /* ufix32 */
  logic [31:0] t_par [0:2];  /* ufix32 [3] */
  logic [31:0] nfp_out_3_1_18;  /* ufix32 */
  logic LowerRelop_out;
  logic [31:0] Saturation2_out1;  /* ufix32 */
  logic [31:0] Saturation1_out1;  /* ufix32 */
  logic [31:0] Cos1_out1;  /* ufix32 */
  logic [31:0] tmp_Dot_Product_dotp_2;  /* ufix32 */
  logic LowerRelop_out_1;
  logic [31:0] nfp_out_1_1_14;  /* ufix32 */
  logic [31:0] nfp_out_1_1_15;  /* ufix32 */
  logic [31:0] nfp_out_1_1_16;  /* ufix32 */
  logic [31:0] nfp_out_1_1_17;  /* ufix32 */
  logic [31:0] t_perp [0:2];  /* ufix32 [3] */
  logic [31:0] nfp_out_1_1_18;  /* ufix32 */
  logic [31:0] Atan2_out1;  /* ufix32 */
  logic LowerRelop_out_2;

  // Unit Thrust
  // Input to PID
  // Desired Unit Thrust
  // Parallel Thrust
  // Perpendicular Thrust
  // Attitude Controller


  nfp_add_single u_nfp_add_comp (.nfp_in1(q_des[0]),  /* single */
                                 .nfp_in2(q[0]),  /* single */
                                 .nfp_out(nfp_out_1_1)  /* single */
                                 );

  nfp_add_single u_nfp_add_comp_1 (.nfp_in1(q_des[1]),  /* single */
                                   .nfp_in2(q[1]),  /* single */
                                   .nfp_out(nfp_out_2_1)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_2 (.nfp_in1(q_des[2]),  /* single */
                                   .nfp_in2(q[2]),  /* single */
                                   .nfp_out(nfp_out_3_1)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_3 (.nfp_in1(q_des[3]),  /* single */
                                   .nfp_in2(q[3]),  /* single */
                                   .nfp_out(nfp_out_4_1)  /* single */
                                   );

  assign Sum3_out1[0] = nfp_out_1_1;
  assign Sum3_out1[1] = nfp_out_2_1;
  assign Sum3_out1[2] = nfp_out_3_1;
  assign Sum3_out1[3] = nfp_out_4_1;

  assign enb = clk_enable;

  always_ff @(posedge clk or posedge reset)
    begin : Unit_Delay5_process
      if (reset == 1'b1) begin
        Unit_Delay5_out1 <= '{4{32'h00000000}};
      end
      else begin
        if (enb) begin
          Unit_Delay5_out1 <= Sum3_out1;
        end
      end
    end
  assign v = Unit_Delay5_out1[0];
  nfp_mul_single u_nfp_mul_comp (.nfp_in1(v),  /* single */
                                 .nfp_in2(Unit_Delay5_out1[0]),  /* single */
                                 .nfp_out(out1)  /* single */
                                 );
  nfp_sqrt_single u_nfp_sqrt_comp (.nfp_in(out1),  /* single */
                                   .nfp_out(norm_v)  /* single */
                                   );
  assign q_0 = Unit_Delay5_out1[1];
  nfp_atan2_single u_nfp_atan2_comp (.nfp_in1(norm_v),  /* single */
                                     .nfp_in2(q_0),  /* single */
                                     .nfp_out(nfp_out_1_1_1)  /* single */
                                     );
  assign pw2_sign_const = 1'b0;

  assign pw2_shift_const = 9'sb000000001;

  nfp_gain_pow2_single u_nfp_gain_pow2_single (.nfp_in1(nfp_out_1_1_1),  /* single */
                                               .nfp_in2(pw2_sign_const),  /* ufix1 */
                                               .nfp_in3(pw2_shift_const),  /* sfix9 */
                                               .nfp_out(nfp_out_1_1_2)  /* single */
                                               );
  nfp_mul_single u_nfp_mul_comp_1 (.nfp_in1(Unit_Delay5_out1[0]),  /* single */
                                   .nfp_in2(nfp_out_1_1_2),  /* single */
                                   .nfp_out(nfp_out_1_1_3)  /* single */
                                   );
  nfp_signum_single u_nfp_signum_comp (.nfp_in(nfp_out_1_1_3),  /* single */
                                       .nfp_out(nfp_out_1_1_4)  /* single */
                                       );

  nfp_mul_single u_nfp_mul_comp_2 (.nfp_in1(nfp_out_1_1_4),  /* single */
                                   .nfp_in2(nfp_out_1_1_3),  /* single */
                                   .nfp_out(nfp_out_1_1_5)  /* single */
                                   );

  nfp_atan2_single u_nfp_atan2_comp_1 (.nfp_in1(norm_v),  /* single */
                                       .nfp_in2(Unit_Delay5_out1[2]),  /* single */
                                       .nfp_out(nfp_out_2_1_1)  /* single */
                                       );

  assign pw2_sign_const_1 = 1'b0;

  assign pw2_shift_const_1 = 9'sb000000001;

  nfp_gain_pow2_single u_nfp_gain_pow2_single_1 (.nfp_in1(nfp_out_2_1_1),  /* single */
                                                 .nfp_in2(pw2_sign_const_1),  /* ufix1 */
                                                 .nfp_in3(pw2_shift_const_1),  /* sfix9 */
                                                 .nfp_out(nfp_out_2_1_2)  /* single */
                                                 );

  nfp_mul_single u_nfp_mul_comp_3 (.nfp_in1(Unit_Delay5_out1[0]),  /* single */
                                   .nfp_in2(nfp_out_2_1_2),  /* single */
                                   .nfp_out(nfp_out_2_1_3)  /* single */
                                   );

  nfp_signum_single u_nfp_signum_comp_1 (.nfp_in(nfp_out_2_1_3),  /* single */
                                         .nfp_out(nfp_out_2_1_4)  /* single */
                                         );

  nfp_mul_single u_nfp_mul_comp_4 (.nfp_in1(nfp_out_2_1_4),  /* single */
                                   .nfp_in2(nfp_out_2_1_3),  /* single */
                                   .nfp_out(nfp_out_2_1_5)  /* single */
                                   );

  nfp_atan2_single u_nfp_atan2_comp_2 (.nfp_in1(norm_v),  /* single */
                                       .nfp_in2(Unit_Delay5_out1[3]),  /* single */
                                       .nfp_out(nfp_out_3_1_1)  /* single */
                                       );

  assign pw2_sign_const_2 = 1'b0;

  assign pw2_shift_const_2 = 9'sb000000001;

  nfp_gain_pow2_single u_nfp_gain_pow2_single_2 (.nfp_in1(nfp_out_3_1_1),  /* single */
                                                 .nfp_in2(pw2_sign_const_2),  /* ufix1 */
                                                 .nfp_in3(pw2_shift_const_2),  /* sfix9 */
                                                 .nfp_out(nfp_out_3_1_2)  /* single */
                                                 );

  nfp_mul_single u_nfp_mul_comp_5 (.nfp_in1(Unit_Delay5_out1[0]),  /* single */
                                   .nfp_in2(nfp_out_3_1_2),  /* single */
                                   .nfp_out(nfp_out_3_1_3)  /* single */
                                   );

  nfp_signum_single u_nfp_signum_comp_2 (.nfp_in(nfp_out_3_1_3),  /* single */
                                         .nfp_out(nfp_out_3_1_4)  /* single */
                                         );

  nfp_mul_single u_nfp_mul_comp_6 (.nfp_in1(nfp_out_3_1_4),  /* single */
                                   .nfp_in2(nfp_out_3_1_3),  /* single */
                                   .nfp_out(nfp_out_3_1_5)  /* single */
                                   );

  assign psi[0] = nfp_out_1_1_5;
  assign psi[1] = nfp_out_2_1_5;
  assign psi[2] = nfp_out_3_1_5;
  always_ff @(posedge clk or posedge reset)
    begin : Unit_Delay6_process
      if (reset == 1'b1) begin
        Unit_Delay6_out1 <= '{3{32'h00000000}};
      end
      else begin
        if (enb) begin
          Unit_Delay6_out1 <= psi;
        end
      end
    end
  Discrete_PID_Controller u_Discrete_PID_Controller (.clk(clk),
                                                     .reset(reset),
                                                     .enb(clk_enable),
                                                     .u(Unit_Delay6_out1),  /* single [3] */
                                                     .y(Discrete_PID_Controller_out1)  /* single [3] */
                                                     );
  nfp_mul_single u_nfp_mul_comp_7 (.nfp_in1(Inertia),  /* single */
                                   .nfp_in2(Angular_Velocity[0]),  /* single */
                                   .nfp_out(nfp_out_1_1_6)  /* single */
                                   );

  nfp_mul_single u_nfp_mul_comp_8 (.nfp_in1(Inertia),  /* single */
                                   .nfp_in2(Angular_Velocity[1]),  /* single */
                                   .nfp_out(nfp_out_2_1_6)  /* single */
                                   );

  nfp_mul_single u_nfp_mul_comp_9 (.nfp_in1(Inertia),  /* single */
                                   .nfp_in2(Angular_Velocity[2]),  /* single */
                                   .nfp_out(nfp_out_3_1_6)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_4 (.nfp_in1(nfp_out_1_1_6),  /* single */
                                   .nfp_in2(Angular_Velocity[0]),  /* single */
                                   .nfp_out(nfp_out_1_1_7)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_5 (.nfp_in1(nfp_out_2_1_6),  /* single */
                                   .nfp_in2(Angular_Velocity[1]),  /* single */
                                   .nfp_out(nfp_out_2_1_7)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_6 (.nfp_in1(nfp_out_3_1_6),  /* single */
                                   .nfp_in2(Angular_Velocity[2]),  /* single */
                                   .nfp_out(nfp_out_3_1_7)  /* single */
                                   );

  assign tau_gyro[0] = nfp_out_1_1_7;
  assign tau_gyro[1] = nfp_out_2_1_7;
  assign tau_gyro[2] = nfp_out_3_1_7;
  always_ff @(posedge clk or posedge reset)
    begin : Unit_Delay7_process
      if (reset == 1'b1) begin
        Unit_Delay7_out1 <= '{3{32'h00000000}};
      end
      else begin
        if (enb) begin
          Unit_Delay7_out1 <= tau_gyro;
        end
      end
    end
  nfp_add_single u_nfp_add_comp_7 (.nfp_in1(Discrete_PID_Controller_out1[0]),  /* single */
                                   .nfp_in2(Unit_Delay7_out1[0]),  /* single */
                                   .nfp_out(nfp_out_1_1_8)  /* single */
                                   );
  nfp_uminus_single u_nfp_uminus_comp (.nfp_in(nfp_out_1_1_8),  /* single */
                                       .nfp_out(nfp_out_1_1_9)  /* single */
                                       );

  nfp_add_single u_nfp_add_comp_8 (.nfp_in1(Discrete_PID_Controller_out1[2]),  /* single */
                                   .nfp_in2(Unit_Delay7_out1[2]),  /* single */
                                   .nfp_out(nfp_out_3_1_8)  /* single */
                                   );

  nfp_uminus_single u_nfp_uminus_comp_1 (.nfp_in(nfp_out_3_1_8),  /* single */
                                         .nfp_out(nfp_out_3_1_9)  /* single */
                                         );

  assign Unit_Delay_ctrl_const_out = 1'b1;

  always_ff @(posedge clk or posedge reset)
    begin : Unit_Delay_ctrl_delay_process
      if (reset == 1'b1) begin
        Unit_Delay_ctrl_delay_out <= 1'b0;
      end
      else begin
        if (enb) begin
          Unit_Delay_ctrl_delay_out <= Unit_Delay_ctrl_const_out;
        end
      end
    end

  assign Unit_Delay_Initial_Val_out = '{3{32'h3f800000}};

  always_ff @(posedge clk or posedge reset)
    begin : Unit_Delay_process
      if (reset == 1'b1) begin
        Unit_Delay_out <= '{3{32'h00000000}};
      end
      else begin
        if (enb) begin
          Unit_Delay_out <= r_gim;
        end
      end
    end
  assign Unit_Delay_out1 = (Unit_Delay_ctrl_delay_out == 1'b0 ? Unit_Delay_Initial_Val_out :
              Unit_Delay_out);

  nfp_mul_single u_nfp_mul_comp_10 (.nfp_in1(Unit_Delay_out1[2]),  /* single */
                                    .nfp_in2(Unit_Delay_out1[2]),  /* single */
                                    .nfp_out(tmp_Dot_Product1_dotp_2)  /* single */
                                    );
  nfp_mul_single u_nfp_mul_comp_11 (.nfp_in1(Unit_Delay_out1[1]),  /* single */
                                    .nfp_in2(Unit_Delay_out1[1]),  /* single */
                                    .nfp_out(tmp_Dot_Product1_dotp_1)  /* single */
                                    );
  nfp_mul_single u_nfp_mul_comp_12 (.nfp_in1(Unit_Delay_out1[0]),  /* single */
                                    .nfp_in2(Unit_Delay_out1[0]),  /* single */
                                    .nfp_out(tmp_Dot_Product1_dotp_0)  /* single */
                                    );
  nfp_add_single u_nfp_add_comp_9 (.nfp_in1(tmp_Dot_Product1_dotp_1),  /* single */
                                   .nfp_in2(tmp_Dot_Product1_dotp_0),  /* single */
                                   .nfp_out(sum_Dot_Product1_dotp_1)  /* single */
                                   );
  nfp_add_single u_nfp_add_comp_10 (.nfp_in1(tmp_Dot_Product1_dotp_2),  /* single */
                                    .nfp_in2(sum_Dot_Product1_dotp_1),  /* single */
                                    .nfp_out(out1_1)  /* single */
                                    );
  always_ff @(posedge clk or posedge reset)
    begin : Unit_Delay2_process
      if (reset == 1'b1) begin
        Unit_Delay2_out1 <= 32'h00000000;
      end
      else begin
        if (enb) begin
          Unit_Delay2_out1 <= out1_1;
        end
      end
    end
  nfp_sqrt_single u_nfp_sqrt_comp_1 (.nfp_in(Unit_Delay2_out1),  /* single */
                                     .nfp_out(Sqrt_out1)  /* single */
                                     );
  assign Upperlimit_out = 32'h3f000000;

  assign Lowerlimit_out = 32'hbf000000;

  nfp_add_single u_nfp_add_comp_11 (.nfp_in1(Discrete_PID_Controller_out1[1]),  /* single */
                                    .nfp_in2(Unit_Delay7_out1[1]),  /* single */
                                    .nfp_out(nfp_out_2_1_8)  /* single */
                                    );

  nfp_uminus_single u_nfp_uminus_comp_2 (.nfp_in(nfp_out_2_1_8),  /* single */
                                         .nfp_out(nfp_out_2_1_9)  /* single */
                                         );

  assign Upperlimit_out_1 = 32'h3f000000;

  assign Lowerlimit_out_1 = 32'hbf000000;

  assign Upperlimit_out_2 = 32'h3f000000;

  assign Lowerlimit_out_2 = 32'hbf000000;

  nfp_relop_single u_nfp_relop_comp (.nfp_in1(theta_x),  /* single */
                                     .nfp_in2(Lowerlimit_out_2),  /* single */
                                     .nfp_out1(UpperRelop_out)
                                     );

  assign Switch1_out = (UpperRelop_out == 1'b0 ? theta_x :
              Lowerlimit_out_2);

  nfp_mul_single u_nfp_mul_comp_13 (.nfp_in1(nfp_out_2_1_10),  /* single */
                                    .nfp_in2(Sqrt2_out1),  /* single */
                                    .nfp_out(nfp_out_2_1_11)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_14 (.nfp_in1(Saturation_out1),  /* single */
                                    .nfp_in2(Product5_out1),  /* single */
                                    .nfp_out(nfp_out_3_1_10)  /* single */
                                    );

  nfp_sub_single u_nfp_sub_comp (.nfp_in1(nfp_out_3_1_9),  /* single */
                                 .nfp_in2(nfp_out_3_1_10),  /* single */
                                 .nfp_out(nfp_out_3_1_11)  /* single */
                                 );

  nfp_add_single u_nfp_add_comp_12 (.nfp_in1(nfp_out_3_1_11),  /* single */
                                    .nfp_in2(Unit_Delay_out1[2]),  /* single */
                                    .nfp_out(nfp_out_3_1_12)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_15 (.nfp_in1(nfp_out_3_1_12),  /* single */
                                    .nfp_in2(out1_1),  /* single */
                                    .nfp_out(nfp_out_3_1_13)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_16 (.nfp_in1(Saturation_out1),  /* single */
                                    .nfp_in2(Gain3_out1),  /* single */
                                    .nfp_out(nfp_out_2_1_12)  /* single */
                                    );

  nfp_sub_single u_nfp_sub_comp_1 (.nfp_in1(nfp_out_2_1_9),  /* single */
                                   .nfp_in2(nfp_out_2_1_12),  /* single */
                                   .nfp_out(nfp_out_2_1_13)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_13 (.nfp_in1(nfp_out_2_1_13),  /* single */
                                    .nfp_in2(Unit_Delay_out1[1]),  /* single */
                                    .nfp_out(nfp_out_2_1_14)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_17 (.nfp_in1(nfp_out_2_1_14),  /* single */
                                    .nfp_in2(out1_1),  /* single */
                                    .nfp_out(nfp_out_2_1_15)  /* single */
                                    );

  nfp_relop_single u_nfp_relop_comp_1 (.nfp_in1(out1_2),  /* single */
                                       .nfp_in2(Lowerlimit_out_1),  /* single */
                                       .nfp_out1(UpperRelop_out_1)
                                       );

  assign Switch1_out_1 = (UpperRelop_out_1 == 1'b0 ? out1_2 :
              Lowerlimit_out_1);

  nfp_mul_single u_nfp_mul_comp_18 (.nfp_in1(nfp_out_1_1_9),  /* single */
                                    .nfp_in2(Sin_out1),  /* single */
                                    .nfp_out(tmp_Dot_Product_dotp_0)  /* single */
                                    );
  nfp_mul_single u_nfp_mul_comp_19 (.nfp_in1(Sin1_out1),  /* single */
                                    .nfp_in2(Cos_out1),  /* single */
                                    .nfp_out(Product4_out1)  /* single */
                                    );
  nfp_uminus_single u_nfp_uminus_comp_3 (.nfp_in(Product4_out1),  /* single */
                                         .nfp_out(Gain3_out1)  /* single */
                                         );
  nfp_mul_single u_nfp_mul_comp_20 (.nfp_in1(nfp_out_2_1_9),  /* single */
                                    .nfp_in2(Gain3_out1),  /* single */
                                    .nfp_out(tmp_Dot_Product_dotp_1)  /* single */
                                    );
  nfp_add_single u_nfp_add_comp_14 (.nfp_in1(tmp_Dot_Product_dotp_1),  /* single */
                                    .nfp_in2(tmp_Dot_Product_dotp_0),  /* single */
                                    .nfp_out(sum_Dot_Product_dotp_1)  /* single */
                                    );
  nfp_relop_single u_nfp_relop_comp_2 (.nfp_in1(theta_y),  /* single */
                                       .nfp_in2(Lowerlimit_out),  /* single */
                                       .nfp_out1(UpperRelop_out_2)
                                       );

  assign Switch1_out_2 = (UpperRelop_out_2 == 1'b0 ? theta_y :
              Lowerlimit_out);

  nfp_mul_single u_nfp_mul_comp_21 (.nfp_in1(nfp_out_1_1_10),  /* single */
                                    .nfp_in2(nfp_out_1_1_10),  /* single */
                                    .nfp_out(tmp_Dot_Product3_dotp_0)  /* single */
                                    );
  nfp_add_single u_nfp_add_comp_15 (.nfp_in1(Unit_Delay1_out1[1]),  /* single */
                                    .nfp_in2(Unit_Delay3_out1[1]),  /* single */
                                    .nfp_out(nfp_out_2_1_10)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_22 (.nfp_in1(nfp_out_2_1_10),  /* single */
                                    .nfp_in2(nfp_out_2_1_10),  /* single */
                                    .nfp_out(tmp_Dot_Product3_dotp_1)  /* single */
                                    );
  nfp_add_single u_nfp_add_comp_16 (.nfp_in1(tmp_Dot_Product3_dotp_1),  /* single */
                                    .nfp_in2(tmp_Dot_Product3_dotp_0),  /* single */
                                    .nfp_out(sum_Dot_Product3_dotp_1)  /* single */
                                    );
  nfp_mul_single u_nfp_mul_comp_23 (.nfp_in1(nfp_out_3_1_14),  /* single */
                                    .nfp_in2(nfp_out_3_1_14),  /* single */
                                    .nfp_out(tmp_Dot_Product3_dotp_2)  /* single */
                                    );
  nfp_add_single u_nfp_add_comp_17 (.nfp_in1(tmp_Dot_Product3_dotp_2),  /* single */
                                    .nfp_in2(sum_Dot_Product3_dotp_1),  /* single */
                                    .nfp_out(out1_3)  /* single */
                                    );
  nfp_sqrt_single u_nfp_sqrt_comp_2 (.nfp_in(out1_3),  /* single */
                                     .nfp_out(Sqrt2_out1)  /* single */
                                     );
  nfp_mul_single u_nfp_mul_comp_24 (.nfp_in1(Subtract_out1),  /* single */
                                    .nfp_in2(Unit_Delay_out1[2]),  /* single */
                                    .nfp_out(nfp_out_3_1_15)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_25 (.nfp_in1(nfp_out_3_1_15),  /* single */
                                    .nfp_in2(Sqrt_out1),  /* single */
                                    .nfp_out(nfp_out_3_1_16)  /* single */
                                    );

  nfp_sqrt_single u_nfp_sqrt_comp_3 (.nfp_in(nfp_out_3_1_16),  /* single */
                                     .nfp_out(nfp_out_3_1_17)  /* single */
                                     );

  nfp_mul_single u_nfp_mul_comp_26 (.nfp_in1(Subtract_out1),  /* single */
                                    .nfp_in2(Unit_Delay_out1[1]),  /* single */
                                    .nfp_out(nfp_out_2_1_16)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_27 (.nfp_in1(nfp_out_2_1_16),  /* single */
                                    .nfp_in2(Sqrt_out1),  /* single */
                                    .nfp_out(nfp_out_2_1_17)  /* single */
                                    );

  nfp_sqrt_single u_nfp_sqrt_comp_4 (.nfp_in(nfp_out_2_1_17),  /* single */
                                     .nfp_out(nfp_out_2_1_18)  /* single */
                                     );

  nfp_mul_single u_nfp_mul_comp_28 (.nfp_in1(Unit_Delay1_out1[0]),  /* single */
                                    .nfp_in2(Unit_Delay1_out1[0]),  /* single */
                                    .nfp_out(tmp_Dot_Product2_dotp_0)  /* single */
                                    );
  nfp_mul_single u_nfp_mul_comp_29 (.nfp_in1(Unit_Delay1_out1[1]),  /* single */
                                    .nfp_in2(Unit_Delay1_out1[1]),  /* single */
                                    .nfp_out(tmp_Dot_Product2_dotp_1)  /* single */
                                    );
  nfp_add_single u_nfp_add_comp_18 (.nfp_in1(tmp_Dot_Product2_dotp_1),  /* single */
                                    .nfp_in2(tmp_Dot_Product2_dotp_0),  /* single */
                                    .nfp_out(sum_Dot_Product2_dotp_1)  /* single */
                                    );
  nfp_mul_single u_nfp_mul_comp_30 (.nfp_in1(Unit_Delay1_out1[2]),  /* single */
                                    .nfp_in2(Unit_Delay1_out1[2]),  /* single */
                                    .nfp_out(tmp_Dot_Product2_dotp_2)  /* single */
                                    );
  nfp_add_single u_nfp_add_comp_19 (.nfp_in1(tmp_Dot_Product2_dotp_2),  /* single */
                                    .nfp_in2(sum_Dot_Product2_dotp_1),  /* single */
                                    .nfp_out(out1_4)  /* single */
                                    );
  nfp_sub_single u_nfp_sub_comp_2 (.nfp_in1(norm_t),  /* single */
                                   .nfp_in2(out1_4),  /* single */
                                   .nfp_out(Subtract_out1)  /* single */
                                   );
  nfp_mul_single u_nfp_mul_comp_31 (.nfp_in1(Subtract_out1),  /* single */
                                    .nfp_in2(Unit_Delay_out1[0]),  /* single */
                                    .nfp_out(nfp_out_1_1_11)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_32 (.nfp_in1(nfp_out_1_1_11),  /* single */
                                    .nfp_in2(Sqrt_out1),  /* single */
                                    .nfp_out(nfp_out_1_1_12)  /* single */
                                    );
  nfp_sqrt_single u_nfp_sqrt_comp_5 (.nfp_in(nfp_out_1_1_12),  /* single */
                                     .nfp_out(nfp_out_1_1_13)  /* single */
                                     );

  assign t_par[0] = nfp_out_1_1_13;
  assign t_par[1] = nfp_out_2_1_18;
  assign t_par[2] = nfp_out_3_1_17;
  always_ff @(posedge clk or posedge reset)
    begin : Unit_Delay3_process
      if (reset == 1'b1) begin
        Unit_Delay3_out1 <= '{3{32'h00000000}};
      end
      else begin
        if (enb) begin
          Unit_Delay3_out1 <= t_par;
        end
      end
    end
  nfp_add_single u_nfp_add_comp_20 (.nfp_in1(Unit_Delay1_out1[2]),  /* single */
                                    .nfp_in2(Unit_Delay3_out1[2]),  /* single */
                                    .nfp_out(nfp_out_3_1_14)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_33 (.nfp_in1(nfp_out_3_1_14),  /* single */
                                    .nfp_in2(Sqrt2_out1),  /* single */
                                    .nfp_out(nfp_out_3_1_18)  /* single */
                                    );

  nfp_asin_single u_nfp_asin_comp (.nfp_in(nfp_out_3_1_18),  /* single */
                                   .nfp_out(theta_y)  /* single */
                                   );
  nfp_relop_single_block u_nfp_relop_comp_3 (.nfp_in1(theta_y),  /* single */
                                             .nfp_in2(Upperlimit_out),  /* single */
                                             .nfp_out1(LowerRelop_out)
                                             );

  assign Saturation2_out1 = (LowerRelop_out == 1'b0 ? Switch1_out_2 :
              Upperlimit_out);
  nfp_sincos_single u_nfp_sincos_comp (.nfp_in(Saturation2_out1),  /* single */
                                       .nfp_out1(Sin_out1),  /* single */
                                       .nfp_out2(Cos_out1)  /* single */
                                       );
  nfp_sincos_single u_nfp_sincos_comp_1 (.nfp_in(Saturation1_out1),  /* single */
                                         .nfp_out1(Sin1_out1),  /* single */
                                         .nfp_out2(Cos1_out1)  /* single */
                                         );
  nfp_mul_single u_nfp_mul_comp_34 (.nfp_in1(Cos1_out1),  /* single */
                                    .nfp_in2(Cos_out1),  /* single */
                                    .nfp_out(Product5_out1)  /* single */
                                    );
  nfp_mul_single u_nfp_mul_comp_35 (.nfp_in1(nfp_out_3_1_9),  /* single */
                                    .nfp_in2(Product5_out1),  /* single */
                                    .nfp_out(tmp_Dot_Product_dotp_2)  /* single */
                                    );
  nfp_add_single u_nfp_add_comp_21 (.nfp_in1(tmp_Dot_Product_dotp_2),  /* single */
                                    .nfp_in2(sum_Dot_Product_dotp_1),  /* single */
                                    .nfp_out(out1_2)  /* single */
                                    );
  nfp_relop_single_block u_nfp_relop_comp_4 (.nfp_in1(out1_2),  /* single */
                                             .nfp_in2(Upperlimit_out_1),  /* single */
                                             .nfp_out1(LowerRelop_out_1)
                                             );

  assign Saturation_out1 = (LowerRelop_out_1 == 1'b0 ? Switch1_out_1 :
              Upperlimit_out_1);
  nfp_mul_single u_nfp_mul_comp_36 (.nfp_in1(Saturation_out1),  /* single */
                                    .nfp_in2(Sin_out1),  /* single */
                                    .nfp_out(nfp_out_1_1_14)  /* single */
                                    );
  nfp_sub_single u_nfp_sub_comp_3 (.nfp_in1(nfp_out_1_1_9),  /* single */
                                   .nfp_in2(nfp_out_1_1_14),  /* single */
                                   .nfp_out(nfp_out_1_1_15)  /* single */
                                   );

  nfp_add_single u_nfp_add_comp_22 (.nfp_in1(nfp_out_1_1_15),  /* single */
                                    .nfp_in2(Unit_Delay_out1[0]),  /* single */
                                    .nfp_out(nfp_out_1_1_16)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_37 (.nfp_in1(nfp_out_1_1_16),  /* single */
                                    .nfp_in2(out1_1),  /* single */
                                    .nfp_out(nfp_out_1_1_17)  /* single */
                                    );

  assign t_perp[0] = nfp_out_1_1_17;
  assign t_perp[1] = nfp_out_2_1_15;
  assign t_perp[2] = nfp_out_3_1_13;
  always_ff @(posedge clk or posedge reset)
    begin : Unit_Delay1_process
      if (reset == 1'b1) begin
        Unit_Delay1_out1 <= '{3{32'h00000000}};
      end
      else begin
        if (enb) begin
          Unit_Delay1_out1 <= t_perp;
        end
      end
    end
  nfp_add_single u_nfp_add_comp_23 (.nfp_in1(Unit_Delay1_out1[0]),  /* single */
                                    .nfp_in2(Unit_Delay3_out1[0]),  /* single */
                                    .nfp_out(nfp_out_1_1_10)  /* single */
                                    );

  nfp_mul_single u_nfp_mul_comp_38 (.nfp_in1(nfp_out_1_1_10),  /* single */
                                    .nfp_in2(Sqrt2_out1),  /* single */
                                    .nfp_out(nfp_out_1_1_18)  /* single */
                                    );

  nfp_atan2_single u_nfp_atan2_comp_3 (.nfp_in1(nfp_out_1_1_18),  /* single */
                                       .nfp_in2(nfp_out_2_1_11),  /* single */
                                       .nfp_out(Atan2_out1)  /* single */
                                       );
  nfp_uminus_single u_nfp_uminus_comp_4 (.nfp_in(Atan2_out1),  /* single */
                                         .nfp_out(theta_x)  /* single */
                                         );
  nfp_relop_single_block u_nfp_relop_comp_5 (.nfp_in1(theta_x),  /* single */
                                             .nfp_in2(Upperlimit_out_2),  /* single */
                                             .nfp_out1(LowerRelop_out_2)
                                             );

  assign Saturation1_out1 = (LowerRelop_out_2 == 1'b0 ? Switch1_out :
              Upperlimit_out_2);
  assign servo_x = Saturation1_out1;

  assign servo_y = Saturation2_out1;

  assign ce_out = clk_enable;

endmodule  // hdl_generation_2

