// -------------------------------------------------------------
// 
// File Name: hdlsrc/hdl_generation_2/nfp_signum_single.sv
// Created: 2025-11-01 20:39:50
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


import hdl_generation_2_pkg::* ;

// -------------------------------------------------------------
// 
// Module: nfp_signum_single
// Source Path: hdl_generation_2/nfp_signum_single
// Hierarchy Level: 1
// Model version: 1.34
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module nfp_signum_single
          (  input logic [31:0] nfp_in  /* ufix32 */,
             output logic [31:0] nfp_out  /* ufix32 */);


  logic X_S;  /* ufix1 */
  logic [7:0] X_E;  /* ufix8 */
  logic [22:0] X_M;  /* ufix23 */
  logic Compare_To_Zero1_out1;  /* ufix1 */
  logic Compare_To_Zero_out1;  /* ufix1 */
  logic Logical_Operator_out1;  /* ufix1 */
  logic Constant2_out1;  /* ufix1 */
  logic Switch1_out1;  /* ufix1 */
  logic Compare_To_Constant_out1;  /* ufix1 */
  logic Logical_Operator1_out1;  /* ufix1 */
  logic Logical_Operator2_out1;  /* ufix1 */
  logic [7:0] Constant_out1;  /* ufix8 */
  logic [7:0] Constant1_out1;  /* ufix8 */
  logic [7:0] Switch_out1;  /* ufix8 */
  logic [7:0] Switch2_out1;  /* ufix8 */
  logic [22:0] Constant3_out1;  /* ufix23 */
  logic [22:0] Switch3_out1;  /* ufix23 */
  logic [31:0] nfp_out_pack;  /* ufix32 */


  // Split 32 bit word into FP sign, exponent, mantissa
  assign X_S = nfp_in[31];
  assign X_E = nfp_in[30:23];
  assign X_M = nfp_in[22:0];

  assign Compare_To_Zero1_out1 = X_E == 8'b00000000;

  assign Compare_To_Zero_out1 = X_M == 23'b00000000000000000000000;

  assign Logical_Operator_out1 = Compare_To_Zero1_out1 & Compare_To_Zero_out1;

  assign Constant2_out1 = 1'b0;

  assign Switch1_out1 = (Logical_Operator_out1 == 1'b0 ? X_S :
              Constant2_out1);

  assign Compare_To_Constant_out1 = (&X_E[7:0]);

  assign Logical_Operator1_out1 =  ~ Compare_To_Zero_out1;

  assign Logical_Operator2_out1 = Compare_To_Constant_out1 & Logical_Operator1_out1;

  assign Constant_out1 = 8'b01111111;

  assign Constant1_out1 = 8'b00000000;

  assign Switch_out1 = (Logical_Operator_out1 == 1'b0 ? Constant_out1 :
              Constant1_out1);

  assign Switch2_out1 = (Logical_Operator2_out1 == 1'b0 ? Switch_out1 :
              X_E);

  assign Constant3_out1 = 23'b00000000000000000000000;

  assign Switch3_out1 = (Logical_Operator2_out1 == 1'b0 ? Constant3_out1 :
              X_M);

  // Combine FP sign, exponent, mantissa into 32 bit word
  assign nfp_out_pack = {Switch1_out1, Switch2_out1, Switch3_out1};

  assign nfp_out = nfp_out_pack;

endmodule  // nfp_signum_single

