// -------------------------------------------------------------
// 
// File Name: hdlsrc/hdl_generation_2/nfp_uminus_single.sv
// Created: 2025-11-01 20:39:50
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


import hdl_generation_2_pkg::* ;

// -------------------------------------------------------------
// 
// Module: nfp_uminus_single
// Source Path: hdl_generation_2/nfp_uminus_single
// Hierarchy Level: 1
// Model version: 1.34
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module nfp_uminus_single
          (  input logic [31:0] nfp_in  /* ufix32 */,
             output logic [31:0] nfp_out  /* ufix32 */);


  logic XS;  /* ufix1 */
  logic [7:0] XE;  /* ufix8 */
  logic [22:0] XM;  /* ufix23 */
  logic Constant1_out1;  /* ufix1 */
  logic Constant_out1;  /* ufix1 */
  logic Switch_out1;  /* ufix1 */
  logic [31:0] nfp_out_pack;  /* ufix32 */


  // Split 32 bit word into FP sign, exponent, mantissa
  assign XS = nfp_in[31];
  assign XE = nfp_in[30:23];
  assign XM = nfp_in[22:0];

  assign Constant1_out1 = 1'b1;

  assign Constant_out1 = 1'b0;

  assign Switch_out1 = (XS == 1'b0 ? Constant1_out1 :
              Constant_out1);

  // Combine FP sign, exponent, mantissa into 32 bit word
  assign nfp_out_pack = {Switch_out1, XE, XM};

  assign nfp_out = nfp_out_pack;

endmodule  // nfp_uminus_single

