// -------------------------------------------------------------
// 
// File Name: hdlsrc/hdl_generation_2/hdl_generation_2_pkg.sv
// Created: 2025-11-01 20:39:50
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------



package hdl_generation_2_pkg;
  typedef  logic  [31:0] vector_of_unsigned_logic_32;

  typedef  logic signed [26:0] vector_of_signed_logic_27;
  typedef  logic  [26:0] vector_of_unsigned_logic_27;

  typedef  logic  [78:0] vector_of_unsigned_logic_79;
endpackage: hdl_generation_2_pkg

