cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('hdl_generation_2/Discrete PID Controller/Anti-windup/Disabled/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Anti-windup/Disabled/Signal Specification2','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/D Gain/Internal Parameters/Signal Specification','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/External Derivative/Error/Signal Specification','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Filter/Disc. Forward Euler Filter/Signal Specification2','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Filter ICs/Internal IC - Filter/Ground','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Filter ICs/Internal IC - Filter/Signal Specification','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Filter ICs/Internal IC - Filter/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_D','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_D0','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_I','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_I0','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_LowerLimit','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_N','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_P','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_Reset','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_TR','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_UpperLimit','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_extAW','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_extTs','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ground_ydot','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/I Gain/Disabled/Signal Specification','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Ideal P Gain Fdbk/Disabled/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Integrator/Disabled/Ground','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Integrator/Disabled/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Integrator/Disabled/Signal Specification4','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Integrator ICs/Disabled/Ground','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Integrator ICs/Disabled/Signal Specification','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Integrator ICs/Disabled/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/N Gain/Internal Parameters/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Parallel P Gain/Internal Parameters/Signal Specification','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Reset Signal/Disabled/Ground','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Reset Signal/Disabled/Signal Specification','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Reset Signal/Disabled/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Saturation/Passthrough/Signal Specification','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Saturation/Passthrough/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Saturation Fdbk/Disabled/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Sum Fdbk/Disabled/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Tracking Mode/Disabled/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Tracking Mode Sum/Passthrough/Signal Specification','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/Tsamp - Integral/TsSignalSpecification/Signal Specification','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/postSat Signal/Forward_Path/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/preInt Signal/Internal PreInt/Signal Specification1','user1');
hilite_system('hdl_generation_2/Discrete PID Controller/preSat Signal/Forward_Path/Signal Specification1','user1');
