// -------------------------------------------------------------
// 
// File Name: hdlsrc/hdl_generation_2/nfp_relop_single_block.sv
// Created: 2025-11-01 20:39:50
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


import hdl_generation_2_pkg::* ;

// -------------------------------------------------------------
// 
// Module: nfp_relop_single_block
// Source Path: hdl_generation_2/nfp_relop_single
// Hierarchy Level: 1
// Model version: 1.34
// 
// {Latency Strategy = "Zero"}
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module nfp_relop_single_block
          (  input logic [31:0] nfp_in1  /* ufix32 */,
             input logic [31:0] nfp_in2  /* ufix32 */,
             output logic nfp_out1  /* ufix1 */);


  logic AS;  /* ufix1 */
  logic [7:0] AE;  /* ufix8 */
  logic [22:0] AM;  /* ufix23 */
  logic [7:0] Constant2_out1;  /* uint8 */
  logic Relational_Operator5_out1;
  logic [22:0] Constant1_out1;  /* ufix23 */
  logic Relational_Operator4_out1;
  logic BS;  /* ufix1 */
  logic [7:0] BE;  /* ufix8 */
  logic [22:0] BM;  /* ufix23 */
  logic Relational_Operator6_out1;
  logic Relational_Operator2_out1;
  logic [7:0] Constant_out1;  /* uint8 */
  logic Relational_Operator3_out1;
  logic Relational_Operator1_out1;
  logic Logical_Operator_out1;
  logic Relational_Operator2_out1_1;
  logic Relational_Operator4_out1_1;
  logic Relational_Operator6_out1_1;
  logic Relational_Operator5_out1_1;
  logic Compare_To_Constant_out1;
  logic Logical_Operator3_out1;
  logic switch_compare_1;
  logic Relational_Operator1_out1_1;
  logic Relational_Operator3_out1_1;
  logic Logical_Operator1_out1;
  logic Logical_Operator2_out1;
  logic Logical_Operator7_out1;
  logic Logical_Operator5_out1;
  logic Constant8_out1;  /* ufix1 */
  logic Logical_Operator1_out1_1;
  logic Logical_Operator4_out1;
  logic Logical_Operator1_out1_2;
  logic Logical_Operator5_out1_1;
  logic Logical_Operator2_out1_1;
  logic Logical_Operator3_out1_1;
  logic Logical_Operator_out1_1;
  logic Logical_Operator6_out1;
  logic Logical_Operator4_out1_1;
  logic Logical_Operator6_out1_1;
  logic Switch_out1;
  logic Logical_Operator4_out1_2;
  logic Logical_Operator5_out1_2;
  logic Constant1_out1_1;
  logic Switch1_out1;


  // Split 32 bit word into FP sign, exponent, mantissa
  assign AS = nfp_in1[31];
  assign AE = nfp_in1[30:23];
  assign AM = nfp_in1[22:0];

  assign Constant2_out1 = 8'b11111111;

  assign Relational_Operator5_out1 = AE == Constant2_out1;

  assign Constant1_out1 = 23'b00000000000000000000000;

  assign Relational_Operator4_out1 = Constant1_out1 == AM;

  // Split 32 bit word into FP sign, exponent, mantissa
  assign BS = nfp_in2[31];
  assign BE = nfp_in2[30:23];
  assign BM = nfp_in2[22:0];

  assign Relational_Operator6_out1 = BE == Constant2_out1;

  assign Relational_Operator2_out1 = Constant1_out1 == BM;

  assign Constant_out1 = 8'b00000000;

  assign Relational_Operator3_out1 = Constant_out1 == BE;

  assign Relational_Operator1_out1 = Constant_out1 == AE;

  assign Logical_Operator_out1 = Relational_Operator4_out1 & (Relational_Operator1_out1 & (Relational_Operator2_out1 & Relational_Operator3_out1));

  assign Relational_Operator2_out1_1 = AS == BS;

  assign Relational_Operator4_out1_1 = AE == BE;

  assign Relational_Operator6_out1_1 = AM == BM;

  assign Relational_Operator5_out1_1 = AS < BS;

  assign Compare_To_Constant_out1 = BS == 1'b1;

  assign Logical_Operator3_out1 = Compare_To_Constant_out1 & Relational_Operator2_out1_1;

  assign switch_compare_1 = Logical_Operator3_out1 > 1'b0;

  assign Relational_Operator1_out1_1 = AE > BE;

  assign Relational_Operator3_out1_1 = AM > BM;

  assign Logical_Operator1_out1 = Relational_Operator4_out1_1 & Relational_Operator3_out1_1;

  assign Logical_Operator2_out1 = Relational_Operator1_out1_1 | Logical_Operator1_out1;

  assign Logical_Operator7_out1 = Relational_Operator2_out1_1 & Logical_Operator2_out1;

  assign Logical_Operator5_out1 =  ~ Logical_Operator7_out1;

  assign Constant8_out1 = 1'b1;

  assign Logical_Operator1_out1_1 =  ~ Constant8_out1;

  assign Logical_Operator4_out1 =  ~ Relational_Operator4_out1;

  assign Logical_Operator1_out1_2 = Relational_Operator5_out1 & Logical_Operator4_out1;

  assign Logical_Operator5_out1_1 =  ~ Relational_Operator2_out1;

  assign Logical_Operator2_out1_1 = Relational_Operator6_out1 & Logical_Operator5_out1_1;

  assign Logical_Operator3_out1_1 = Logical_Operator1_out1_2 | Logical_Operator2_out1_1;

  assign Logical_Operator_out1_1 = Logical_Operator1_out1_1 | Logical_Operator3_out1_1;

  assign Logical_Operator6_out1 = Relational_Operator6_out1_1 & (Relational_Operator2_out1_1 & Relational_Operator4_out1_1);

  assign Logical_Operator4_out1_1 = Logical_Operator_out1 | Logical_Operator6_out1;

  assign Logical_Operator6_out1_1 =  ~ Logical_Operator4_out1_1;

  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Logical_Operator7_out1 :
              Logical_Operator5_out1);

  assign Logical_Operator4_out1_2 = Relational_Operator5_out1_1 | Switch_out1;

  assign Logical_Operator5_out1_2 = Logical_Operator6_out1_1 & Logical_Operator4_out1_2;

  assign Constant1_out1_1 = 1'b0;

  assign Switch1_out1 = (Logical_Operator_out1_1 == 1'b0 ? Logical_Operator5_out1_2 :
              Constant1_out1_1);

  assign nfp_out1 = Switch1_out1;

endmodule  // nfp_relop_single_block

