// -------------------------------------------------------------
// 
// File Name: hdlsrc/hdl_generation_2/nfp_asin_single.sv
// Created: 2025-11-01 20:39:50
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


import hdl_generation_2_pkg::* ;

// -------------------------------------------------------------
// 
// Module: nfp_asin_single
// Source Path: hdl_generation_2/nfp_asin_single
// Hierarchy Level: 1
// Model version: 1.34
// 
// {Latency Strategy = "Zero"}
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module nfp_asin_single
          (  input logic [31:0] nfp_in  /* ufix32 */,
             output logic [31:0] nfp_out  /* ufix32 */);


  logic S;  /* ufix1 */
  logic [7:0] E;  /* ufix8 */
  logic [22:0] M;  /* ufix23 */
  logic Constant8_out1;  /* ufix1 */
  logic [7:0] Constant_out1;  /* uint8 */
  logic Compare_To_Constant_out1;
  logic Compare_To_Zero_out1;
  logic Logical_Operator_out1;
  logic [7:0] alpha127_out1;  /* uint8 */
  logic signed [31:0] Subtract_sub_temp;  /* sfix32 */
  logic signed [31:0] Subtract_1;  /* sfix32 */
  logic signed [31:0] Subtract_2;  /* sfix32 */
  logic signed [8:0] Subtract_out1;  /* sfix9 */
  logic signed [7:0] alpha1_out1;  /* int8 */
  logic signed [8:0] Relational_Operator_1;  /* sfix9 */
  logic Relational_Operator_out1;
  logic exp_0_out1;
  logic c1_out1;
  logic signed [7:0] C_out1;  /* int8 */
  logic signed [8:0] C_out1_dtc;  /* sfix9 */
  logic signed [8:0] s2_out1;  /* sfix9 */
  logic signed [8:0] if_exp_0_out1;  /* sfix9 */
  logic compare2_out1;
  logic Constant_out1_1;  /* ufix1 */
  logic [23:0] Bit_Concat_out1;  /* ufix24 */
  logic [23:0] Data_Type_Conversion_out1;  /* ufix24_En23 */
  logic [35:0] DTC_out1;  /* ufix36_En35 */
  logic signed [9:0] alphaexp_in0;  /* sfix10 */
  logic signed [9:0] alphaexp_1;  /* sfix10 */
  logic signed [8:0] alphaexp_out1;  /* sfix9 */
  logic [5:0] Data_Type_Conversion_out1_1;  /* ufix6 */
  logic [7:0] dynamic_shift_cast;  /* uint8 */
  logic [35:0] bitsra_x_wide_exp_out1;  /* ufix36_En35 */
  logic [35:0] if_exp_0_1_out1;  /* ufix36_En35 */
  logic [5:0] BitSlice_out1;  /* ufix6 */
  logic [7:0] DTC1_out1;  /* uint8 */
  logic [7:0] Constant_out1_2;  /* uint8 */
  logic Relational_Operator_out1_1;
  logic Logical_Operator1_out1;
  logic [7:0] DTC5_out1;  /* uint8 */
  vector_of_signed_logic_27 coeffs_table_two_out1 [0:63];  /* sfix27_En25 [64] */
  logic signed [26:0] sqrt_coeffs_table_domain_2_1_out1;  /* sfix27_En25 */
  logic [7:0] DTC4_out1;  /* uint8 */
  vector_of_signed_logic_27 coeffs_table_three_out1 [0:63];  /* sfix27_En25 [64] */
  logic signed [26:0] sqrt_coeffs_table_domain_3_out1;  /* sfix27_En25 */
  logic signed [26:0] DTC3_out1;  /* sfix27_En25 */
  logic signed [53:0] res_x_mul_temp;  /* sfix54_En50 */
  logic signed [26:0] res_x_out1;  /* sfix27_En25 */
  logic signed [31:0] res_x_coeffs_3_1_add_cast;  /* sfix32_En25 */
  logic signed [31:0] res_x_coeffs_3_1_add_cast_1;  /* sfix32_En25 */
  logic signed [31:0] res_x_coeffs_3_1_add_temp;  /* sfix32_En25 */
  logic signed [26:0] res_x_coeffs_3_1_out1;  /* sfix27_En25 */
  logic [7:0] DTC2_out1;  /* uint8 */
  logic signed [53:0] res_x_mul_temp_1;  /* sfix54_En50 */
  logic signed [26:0] res_x_out1_1;  /* sfix27_En25 */
  vector_of_signed_logic_27 coeffs_table_one_out1 [0:63];  /* sfix27_En25 [64] */
  logic signed [26:0] sqrt_coeffs_table_domain_1_out1;  /* sfix27_En25 */
  logic signed [31:0] res_x_coeffs_2_1_add_cast;  /* sfix32_En25 */
  logic signed [31:0] res_x_coeffs_2_1_add_cast_1;  /* sfix32_En25 */
  logic signed [31:0] res_x_coeffs_2_1_add_temp;  /* sfix32_En25 */
  logic signed [26:0] res_x_coeffs_2_1_out1;  /* sfix27_En25 */
  logic [26:0] Bit_Slice_out1;  /* ufix27 */
  logic cmp3_out1;
  logic cmp0_out1;
  logic cmp1_out1;
  logic Logical_Operator_out1_1;
  logic [35:0] c1_out1_1;  /* ufix36_En35 */
  logic [35:0] add1_sub_temp;  /* ufix36_En35 */
  logic [36:0] add1_out1;  /* ufix37_En36 */
  logic [35:0] Data_Type_Conversion_out1_2;  /* ufix36 */
  logic Bit_Slice1_out1;  /* ufix1 */
  logic signed [7:0] Constant45_out1;  /* int8 */
  logic Bit_Slice35_out1;  /* ufix1 */
  logic signed [7:0] Constant1_out1;  /* int8 */
  logic signed [7:0] Switch1_out1;  /* int8 */
  logic Bit_Slice34_out1;  /* ufix1 */
  logic signed [7:0] Constant44_out1;  /* int8 */
  logic signed [7:0] Switch46_out1;  /* int8 */
  logic Bit_Slice33_out1;  /* ufix1 */
  logic signed [7:0] Constant43_out1;  /* int8 */
  logic signed [7:0] Switch45_out1;  /* int8 */
  logic Bit_Slice32_out1;  /* ufix1 */
  logic signed [7:0] Constant42_out1;  /* int8 */
  logic signed [7:0] Switch44_out1;  /* int8 */
  logic Bit_Slice31_out1;  /* ufix1 */
  logic signed [7:0] Constant41_out1;  /* int8 */
  logic signed [7:0] Switch43_out1;  /* int8 */
  logic Bit_Slice42_out1;  /* ufix1 */
  logic signed [7:0] Constant39_out1;  /* int8 */
  logic signed [7:0] Switch42_out1;  /* int8 */
  logic Bit_Slice41_out1;  /* ufix1 */
  logic signed [7:0] Constant38_out1;  /* int8 */
  logic signed [7:0] Switch41_out1;  /* int8 */
  logic Bit_Slice40_out1;  /* ufix1 */
  logic signed [7:0] Constant37_out1;  /* int8 */
  logic signed [7:0] Switch40_out1;  /* int8 */
  logic Bit_Slice39_out1;  /* ufix1 */
  logic signed [7:0] Constant36_out1;  /* int8 */
  logic signed [7:0] Switch39_out1;  /* int8 */
  logic Bit_Slice37_out1;  /* ufix1 */
  logic signed [7:0] Constant35_out1;  /* int8 */
  logic signed [7:0] Switch34_out1;  /* int8 */
  logic Bit_Slice36_out1;  /* ufix1 */
  logic signed [7:0] Constant34_out1;  /* int8 */
  logic signed [7:0] Switch33_out1;  /* int8 */
  logic Bit_Slice30_out1;  /* ufix1 */
  logic signed [7:0] Constant33_out1;  /* int8 */
  logic signed [7:0] Switch32_out1;  /* int8 */
  logic Bit_Slice29_out1;  /* ufix1 */
  logic signed [7:0] Constant32_out1;  /* int8 */
  logic signed [7:0] Switch31_out1;  /* int8 */
  logic Bit_Slice53_out1;  /* ufix1 */
  logic signed [7:0] Constant31_out1;  /* int8 */
  logic signed [7:0] Switch30_out1;  /* int8 */
  logic Bit_Slice52_out1;  /* ufix1 */
  logic signed [7:0] Constant30_out1;  /* int8 */
  logic signed [7:0] Switch29_out1;  /* int8 */
  logic Bit_Slice51_out1;  /* ufix1 */
  logic signed [7:0] Constant55_out1;  /* int8 */
  logic signed [7:0] Switch53_out1;  /* int8 */
  logic Bit_Slice49_out1;  /* ufix1 */
  logic signed [7:0] Constant54_out1;  /* int8 */
  logic signed [7:0] Switch52_out1;  /* int8 */
  logic Bit_Slice48_out1;  /* ufix1 */
  logic signed [7:0] Constant53_out1;  /* int8 */
  logic signed [7:0] Switch51_out1;  /* int8 */
  logic Bit_Slice47_out1;  /* ufix1 */
  logic signed [7:0] Constant52_out1;  /* int8 */
  logic signed [7:0] Switch50_out1;  /* int8 */
  logic Bit_Slice38_out1;  /* ufix1 */
  logic signed [7:0] Constant51_out1;  /* int8 */
  logic signed [7:0] Switch49_out1;  /* int8 */
  logic Bit_Slice28_out1;  /* ufix1 */
  logic signed [7:0] Constant50_out1;  /* int8 */
  logic signed [7:0] Switch48_out1;  /* int8 */
  logic Bit_Slice17_out1;  /* ufix1 */
  logic signed [7:0] Constant49_out1;  /* int8 */
  logic signed [7:0] Switch47_out1;  /* int8 */
  logic Bit_Slice45_out1;  /* ufix1 */
  logic signed [7:0] Constant40_out1;  /* int8 */
  logic signed [7:0] Switch38_out1;  /* int8 */
  logic Bit_Slice44_out1;  /* ufix1 */
  logic signed [7:0] Constant29_out1;  /* int8 */
  logic signed [7:0] Switch28_out1;  /* int8 */
  logic Bit_Slice43_out1;  /* ufix1 */
  logic signed [7:0] Constant27_out1;  /* int8 */
  logic signed [7:0] Switch19_out1;  /* int8 */
  logic Bit_Slice46_out1;  /* ufix1 */
  logic signed [7:0] Constant56_out1;  /* int8 */
  logic signed [7:0] Switch55_out1;  /* int8 */
  logic Bit_Slice16_out1;  /* ufix1 */
  logic signed [7:0] Constant28_out1;  /* int8 */
  logic signed [7:0] Switch54_out1;  /* int8 */
  logic Bit_Slice15_out1;  /* ufix1 */
  logic signed [7:0] Constant26_out1;  /* int8 */
  logic signed [7:0] Switch18_out1;  /* int8 */
  logic Bit_Slice14_out1;  /* ufix1 */
  logic signed [7:0] Constant25_out1;  /* int8 */
  logic signed [7:0] Switch17_out1;  /* int8 */
  logic Bit_Slice13_out1;  /* ufix1 */
  logic signed [7:0] Constant24_out1;  /* int8 */
  logic signed [7:0] Switch16_out1;  /* int8 */
  logic Bit_Slice12_out1;  /* ufix1 */
  logic signed [7:0] Constant23_out1;  /* int8 */
  logic signed [7:0] Switch27_out1;  /* int8 */
  logic Bit_Slice23_out1;  /* ufix1 */
  logic signed [7:0] Constant22_out1;  /* int8 */
  logic signed [7:0] Switch26_out1;  /* int8 */
  logic Bit_Slice22_out1;  /* ufix1 */
  logic signed [7:0] Constant21_out1;  /* int8 */
  logic signed [7:0] Switch25_out1;  /* int8 */
  logic Bit_Slice21_out1;  /* ufix1 */
  logic signed [7:0] Constant20_out1;  /* int8 */
  logic signed [7:0] Switch24_out1;  /* int8 */
  logic signed [7:0] Constant19_out1;  /* int8 */
  logic signed [7:0] Switch23_out1;  /* int8 */
  logic signed [8:0] Unary_Minus_in0;  /* sfix9 */
  logic signed [8:0] Unary_Minus_1;  /* sfix9 */
  logic signed [7:0] Unary_Minus_out1;  /* int8 */
  logic BitSlice3_out1;  /* ufix1 */
  logic bitsliceget_s_e_1_2_out1;
  logic signed [7:0] BitClear_out1;  /* int8 */
  logic signed [7:0] s1_out1;  /* int8 */
  logic cmp1_out1_1;
  logic [5:0] Data_Type_Conversion2_out1;  /* ufix6 */
  logic [7:0] dynamic_shift_2;  /* uint8 */
  logic [35:0] Shift_Arithmetic_out1;  /* ufix36 */
  logic [35:0] Data_Type_Conversion1_out1;  /* ufix36_En36 */
  logic [26:0] DTC_out1_1;  /* ufix27_En27 */
  logic [4:0] BitSlice_out1_1;  /* ufix5 */
  logic [7:0] DTC2_out1_1;  /* uint8 */
  vector_of_signed_logic_27 sqrt_coeffs_table_out1 [0:31];  /* sfix27_En26 [32] */
  logic signed [26:0] sqrt_coeffs_table_domain_3_out1_1;  /* sfix27_En26 */
  logic [7:0] DTC7_out1;  /* uint8 */
  logic signed [27:0] res_s_m_cast;  /* sfix28_En27 */
  logic signed [54:0] res_s_m_mul_temp;  /* sfix55_En53 */
  logic signed [53:0] res_s_m_cast_1;  /* sfix54_En53 */
  logic signed [26:0] res_s_m_out1;  /* sfix27_En26 */
  vector_of_unsigned_logic_27 sqrt_coeffs_table_out1_1 [0:31];  /* ufix27_En26 [32] */
  logic [26:0] sqrt_coeffs_table_domain_2_out1;  /* ufix27_En26 */
  logic signed [31:0] res_s_m_coeffs_two_add_cast;  /* sfix32_En26 */
  logic signed [31:0] res_s_m_coeffs_two_add_cast_1;  /* sfix32_En26 */
  logic signed [31:0] res_s_m_coeffs_two_add_temp;  /* sfix32_En26 */
  logic signed [26:0] res_s_m_coeffs_two_out1;  /* sfix27_En26 */
  logic [26:0] DTC5_out1_1;  /* ufix27_En26 */
  logic [7:0] DTC1_out1_1;  /* uint8 */
  logic [53:0] res_s_m_mul_temp_1;  /* ufix54_En53 */
  logic [26:0] res_s_m_out1_1;  /* ufix27_En26 */
  vector_of_signed_logic_27 sqrt_coeffs_table_out1_2 [0:31];  /* sfix27_En26 [32] */
  logic signed [26:0] sqrt_coeffs_table_domain_1_out1_1;  /* sfix27_En26 */
  logic [26:0] DTC6_out1;  /* ufix27_En27 */
  logic [31:0] res_s_m_coeffs_one_add_cast;  /* ufix32_En27 */
  logic [31:0] res_s_m_coeffs_one_add_cast_1;  /* ufix32_En27 */
  logic [31:0] res_s_m_coeffs_one_add_temp;  /* ufix32_En27 */
  logic [26:0] res_s_m_coeffs_one_out1;  /* ufix27_En26 */
  logic [26:0] c2_out1;  /* ufix27_En26 */
  logic [53:0] mul1_mul_temp;  /* ufix54_En52 */
  logic [26:0] mul1_out1;  /* ufix27_En26 */
  logic [26:0] s3_out1;  /* ufix27_En26 */
  logic [35:0] dtc3_out1_1;  /* ufix36_En35 */
  logic signed [7:0] bitsra_s_e_1_out1;  /* int8 */
  logic signed [8:0] alphas_e_in0;  /* sfix9 */
  logic signed [8:0] alphas_e_1;  /* sfix9 */
  logic signed [7:0] alphas_e_out1;  /* int8 */
  logic [5:0] dtc4_out1_1;  /* ufix6 */
  logic [7:0] dynamic_shift_cast_1;  /* uint8 */
  logic [35:0] bitsra_y_s_e_out1;  /* ufix36_En35 */
  logic [35:0] s2_out1_1;  /* ufix36_En35 */
  logic [35:0] compare_out1;  /* ufix36_En35 */
  logic [26:0] Bit_Slice2_out1;  /* ufix27 */
  logic [8:0] Bit_Slice1_out1_1;  /* ufix9 */
  logic [53:0] z0_out1;  /* ufix54 */
  logic [35:0] z1_out1;  /* ufix36 */
  logic [63:0] Data_Type_Conversion_out1_3;  /* ufix64 */
  logic [63:0] Bit_Shift_out1;  /* ufix64 */
  logic [63:0] Sum_1;  /* ufix64 */
  logic [63:0] Sum_out1;  /* ufix64 */
  logic [63:0] Data_Type_Conversion4_out1;  /* ufix64_En60 */
  logic [35:0] Data_Type_Conversion3_out1;  /* ufix36_En35 */
  logic [35:0] C2_out1_1;  /* ufix36_En35 */
  logic [35:0] Add_out1;  /* ufix36_En35 */
  logic [35:0] compare1_out1;  /* ufix36_En35 */
  logic [35:0] compare3_out1;  /* ufix36_En35 */
  logic cmp0_out1_1;
  logic [7:0] alpha127_out1_1;  /* uint8 */
  logic [35:0] Data_Type_Conversion1_out1_1;  /* ufix36_En34 */
  logic [35:0] Data_Type_Conversion_out1_4;  /* ufix36 */
  logic Bit_Slice35_out1_1;  /* ufix1 */
  logic signed [7:0] Constant45_out1_1;  /* int8 */
  logic Bit_Slice34_out1_1;  /* ufix1 */
  logic signed [7:0] Constant44_out1_1;  /* int8 */
  logic signed [7:0] Switch46_out1_1;  /* int8 */
  logic Bit_Slice33_out1_1;  /* ufix1 */
  logic signed [7:0] Constant43_out1_1;  /* int8 */
  logic signed [7:0] Switch45_out1_1;  /* int8 */
  logic Bit_Slice32_out1_1;  /* ufix1 */
  logic signed [7:0] Constant42_out1_1;  /* int8 */
  logic signed [7:0] Switch44_out1_1;  /* int8 */
  logic Bit_Slice31_out1_1;  /* ufix1 */
  logic signed [7:0] Constant41_out1_1;  /* int8 */
  logic signed [7:0] Switch43_out1_1;  /* int8 */
  logic Bit_Slice42_out1_1;  /* ufix1 */
  logic signed [7:0] Constant39_out1_1;  /* int8 */
  logic signed [7:0] Switch42_out1_1;  /* int8 */
  logic Bit_Slice41_out1_1;  /* ufix1 */
  logic signed [7:0] Constant38_out1_1;  /* int8 */
  logic signed [7:0] Switch41_out1_1;  /* int8 */
  logic Bit_Slice40_out1_1;  /* ufix1 */
  logic signed [7:0] Constant37_out1_1;  /* int8 */
  logic signed [7:0] Switch40_out1_1;  /* int8 */
  logic Bit_Slice39_out1_1;  /* ufix1 */
  logic signed [7:0] Constant36_out1_1;  /* int8 */
  logic signed [7:0] Switch39_out1_1;  /* int8 */
  logic Bit_Slice37_out1_1;  /* ufix1 */
  logic signed [7:0] Constant35_out1_1;  /* int8 */
  logic signed [7:0] Switch34_out1_1;  /* int8 */
  logic Bit_Slice36_out1_1;  /* ufix1 */
  logic signed [7:0] Constant34_out1_1;  /* int8 */
  logic signed [7:0] Switch33_out1_1;  /* int8 */
  logic Bit_Slice30_out1_1;  /* ufix1 */
  logic signed [7:0] Constant33_out1_1;  /* int8 */
  logic signed [7:0] Switch32_out1_1;  /* int8 */
  logic Bit_Slice29_out1_1;  /* ufix1 */
  logic signed [7:0] Constant32_out1_1;  /* int8 */
  logic signed [7:0] Switch31_out1_1;  /* int8 */
  logic Bit_Slice53_out1_1;  /* ufix1 */
  logic signed [7:0] Constant31_out1_1;  /* int8 */
  logic signed [7:0] Switch30_out1_1;  /* int8 */
  logic Bit_Slice52_out1_1;  /* ufix1 */
  logic signed [7:0] Constant30_out1_1;  /* int8 */
  logic signed [7:0] Switch29_out1_1;  /* int8 */
  logic Bit_Slice51_out1_1;  /* ufix1 */
  logic signed [7:0] Constant55_out1_1;  /* int8 */
  logic signed [7:0] Switch53_out1_1;  /* int8 */
  logic Bit_Slice49_out1_1;  /* ufix1 */
  logic signed [7:0] Constant54_out1_1;  /* int8 */
  logic signed [7:0] Switch52_out1_1;  /* int8 */
  logic Bit_Slice48_out1_1;  /* ufix1 */
  logic signed [7:0] Constant53_out1_1;  /* int8 */
  logic signed [7:0] Switch51_out1_1;  /* int8 */
  logic Bit_Slice47_out1_1;  /* ufix1 */
  logic signed [7:0] Constant52_out1_1;  /* int8 */
  logic signed [7:0] Switch50_out1_1;  /* int8 */
  logic Bit_Slice38_out1_1;  /* ufix1 */
  logic signed [7:0] Constant51_out1_1;  /* int8 */
  logic signed [7:0] Switch49_out1_1;  /* int8 */
  logic Bit_Slice28_out1_1;  /* ufix1 */
  logic signed [7:0] Constant50_out1_1;  /* int8 */
  logic signed [7:0] Switch48_out1_1;  /* int8 */
  logic Bit_Slice17_out1_1;  /* ufix1 */
  logic signed [7:0] Constant49_out1_1;  /* int8 */
  logic signed [7:0] Switch47_out1_1;  /* int8 */
  logic Bit_Slice45_out1_1;  /* ufix1 */
  logic signed [7:0] Constant40_out1_1;  /* int8 */
  logic signed [7:0] Switch38_out1_1;  /* int8 */
  logic Bit_Slice44_out1_1;  /* ufix1 */
  logic signed [7:0] Constant29_out1_1;  /* int8 */
  logic signed [7:0] Switch28_out1_1;  /* int8 */
  logic Bit_Slice43_out1_1;  /* ufix1 */
  logic signed [7:0] Constant27_out1_1;  /* int8 */
  logic signed [7:0] Switch19_out1_1;  /* int8 */
  logic Bit_Slice46_out1_1;  /* ufix1 */
  logic signed [7:0] Constant56_out1_1;  /* int8 */
  logic signed [7:0] Switch55_out1_1;  /* int8 */
  logic Bit_Slice16_out1_1;  /* ufix1 */
  logic signed [7:0] Constant28_out1_1;  /* int8 */
  logic signed [7:0] Switch54_out1_1;  /* int8 */
  logic Bit_Slice15_out1_1;  /* ufix1 */
  logic signed [7:0] Constant26_out1_1;  /* int8 */
  logic signed [7:0] Switch18_out1_1;  /* int8 */
  logic Bit_Slice14_out1_1;  /* ufix1 */
  logic signed [7:0] Constant25_out1_1;  /* int8 */
  logic signed [7:0] Switch17_out1_1;  /* int8 */
  logic Bit_Slice13_out1_1;  /* ufix1 */
  logic signed [7:0] Constant24_out1_1;  /* int8 */
  logic signed [7:0] Switch16_out1_1;  /* int8 */
  logic Bit_Slice12_out1_1;  /* ufix1 */
  logic signed [7:0] Constant23_out1_1;  /* int8 */
  logic signed [7:0] Switch27_out1_1;  /* int8 */
  logic Bit_Slice23_out1_1;  /* ufix1 */
  logic signed [7:0] Constant22_out1_1;  /* int8 */
  logic signed [7:0] Switch26_out1_1;  /* int8 */
  logic Bit_Slice22_out1_1;  /* ufix1 */
  logic signed [7:0] Constant21_out1_1;  /* int8 */
  logic signed [7:0] Switch25_out1_1;  /* int8 */
  logic Bit_Slice21_out1_1;  /* ufix1 */
  logic signed [7:0] Constant20_out1_1;  /* int8 */
  logic signed [7:0] Switch24_out1_1;  /* int8 */
  logic Bit_Slice20_out1;  /* ufix1 */
  logic signed [7:0] Constant19_out1_1;  /* int8 */
  logic signed [7:0] Switch23_out1_1;  /* int8 */
  logic signed [7:0] Constant18_out1;  /* int8 */
  logic signed [7:0] Switch22_out1;  /* int8 */
  logic signed [31:0] Sum_sub_temp;  /* sfix32 */
  logic signed [31:0] Sum_3;  /* sfix32 */
  logic signed [31:0] Sum_4;  /* sfix32 */
  logic [7:0] Sum_out1_1;  /* uint8 */
  logic [7:0] E0_out1;  /* uint8 */
  logic [7:0] s5_out1;  /* uint8 */
  logic [7:0] PipelinePath_out1_dtc;  /* uint8 */
  logic [7:0] s0_out1;  /* uint8 */
  logic [7:0] E1_out1;  /* uint8 */
  logic [7:0] s4_out1;  /* uint8 */
  logic [7:0] Switch1_out1_1;  /* uint8 */
  logic [22:0] Constant1_out1_1;  /* ufix23 */
  logic switch_compare_1;
  logic [35:0] Bit_Shift_out1_1;  /* ufix36 */
  logic [5:0] Data_Type_Conversion2_out1_1;  /* ufix6 */
  logic [7:0] dynamic_shift_5;  /* uint8 */
  logic [35:0] Shift_Arithmetic_out1_1;  /* ufix36 */
  logic [35:0] Switch_out1;  /* ufix36 */
  logic [22:0] Bit_Slice1_out1_2;  /* ufix23 */
  logic [22:0] M0_out1;  /* ufix23 */
  logic [22:0] s6_out1;  /* ufix23 */
  logic [22:0] s1_out1_1;  /* ufix23 */
  logic [22:0] Bit_Set_out1;  /* ufix23 */
  logic [22:0] s2_out1_2;  /* ufix23 */
  logic [22:0] Switch_out1_1;  /* ufix23 */
  logic [31:0] nfp_out_pack;  /* ufix32 */


  // Split 32 bit word into FP sign, exponent, mantissa
  assign S = nfp_in[31];
  assign E = nfp_in[30:23];
  assign M = nfp_in[22:0];

  assign Constant8_out1 = 1'b1;

  assign Constant_out1 = 8'b00000000;

  assign Compare_To_Constant_out1 = E == 8'b11111111;

  assign Compare_To_Zero_out1 = M != 23'b00000000000000000000000;

  assign Logical_Operator_out1 = Compare_To_Constant_out1 & Compare_To_Zero_out1;

  assign alpha127_out1 = 8'b01111111;

  assign Subtract_1 = {24'b0, E};
  assign Subtract_2 = {24'b0, alpha127_out1};
  assign Subtract_sub_temp = Subtract_1 - Subtract_2;
  assign Subtract_out1 = Subtract_sub_temp[8:0];

  assign alpha1_out1 = 8'sb11110100;

  assign Relational_Operator_1 = {alpha1_out1[7], alpha1_out1};
  assign Relational_Operator_out1 = Subtract_out1 < Relational_Operator_1;

  assign exp_0_out1 = Subtract_out1 < 9'sb000000000;

  assign c1_out1 = Subtract_out1 < 9'sb111011101;

  assign C_out1 = 8'sb11011101;

  assign C_out1_dtc = {C_out1[7], C_out1};

  assign s2_out1 = (c1_out1 == 1'b0 ? Subtract_out1 :
              C_out1_dtc);

  assign if_exp_0_out1 = (exp_0_out1 == 1'b0 ? Subtract_out1 :
              s2_out1);

  assign compare2_out1 = if_exp_0_out1 >= 9'sb000000000;

  assign Constant_out1_1 = 1'b1;

  assign Bit_Concat_out1 = {Constant_out1_1, M};

  assign Data_Type_Conversion_out1 = Bit_Concat_out1;

  assign DTC_out1 = {Data_Type_Conversion_out1, 12'b000000000000};

  assign alphaexp_1 = {s2_out1[8], s2_out1};
  assign alphaexp_in0 =  - (alphaexp_1);
  assign alphaexp_out1 = alphaexp_in0[8:0];

  assign Data_Type_Conversion_out1_1 = alphaexp_out1[5:0];

  assign dynamic_shift_cast = {2'b0, Data_Type_Conversion_out1_1};
  assign bitsra_x_wide_exp_out1 = DTC_out1 >>> dynamic_shift_cast;

  assign if_exp_0_1_out1 = (exp_0_out1 == 1'b0 ? DTC_out1 :
              bitsra_x_wide_exp_out1);

  assign BitSlice_out1 = if_exp_0_1_out1[34:29];

  assign DTC1_out1 = {2'b0, BitSlice_out1};

  assign Constant_out1_2 = 8'b00100000;

  assign Relational_Operator_out1_1 = DTC1_out1 < Constant_out1_2;

  assign Logical_Operator1_out1 =  ~ Relational_Operator_out1_1;

  assign DTC5_out1 = {2'b0, BitSlice_out1};

  assign coeffs_table_two_out1[0] = 27'sb111111111111111111111110111;
  assign coeffs_table_two_out1[1] = 27'sb111111111111111111011111110;
  assign coeffs_table_two_out1[2] = 27'sb111111111111111101101010000;
  assign coeffs_table_two_out1[3] = 27'sb111111111111111001100010101;
  assign coeffs_table_two_out1[4] = 27'sb111111111111110010001110000;
  assign coeffs_table_two_out1[5] = 27'sb111111111111100110101110001;
  assign coeffs_table_two_out1[6] = 27'sb111111111111010110000011000;
  assign coeffs_table_two_out1[7] = 27'sb111111111110111111001001100;
  assign coeffs_table_two_out1[8] = 27'sb111111111110100000111010110;
  assign coeffs_table_two_out1[9] = 27'sb111111111101111010001011111;
  assign coeffs_table_two_out1[10] = 27'sb111111111101001001101100110;
  assign coeffs_table_two_out1[11] = 27'sb111111111100001110000111010;
  assign coeffs_table_two_out1[12] = 27'sb111111111011000101111110111;
  assign coeffs_table_two_out1[13] = 27'sb111111111001101111101110101;
  assign coeffs_table_two_out1[14] = 27'sb111111111000001001101001000;
  assign coeffs_table_two_out1[15] = 27'sb111111110110010001110110000;
  assign coeffs_table_two_out1[16] = 27'sb111111110100000110010001110;
  assign coeffs_table_two_out1[17] = 27'sb111111110001100100101010111;
  assign coeffs_table_two_out1[18] = 27'sb111111101110101010100000010;
  assign coeffs_table_two_out1[19] = 27'sb111111101011010100111111101;
  assign coeffs_table_two_out1[20] = 27'sb111111100111100001000001101;
  assign coeffs_table_two_out1[21] = 27'sb111111100011001011001000000;
  assign coeffs_table_two_out1[22] = 27'sb111111011110001111011001011;
  assign coeffs_table_two_out1[23] = 27'sb111111011000101001011101100;
  assign coeffs_table_two_out1[24] = 27'sb111111010010010100011000000;
  assign coeffs_table_two_out1[25] = 27'sb111111001011001010100011010;
  assign coeffs_table_two_out1[26] = 27'sb111111000011000101101000111;
  assign coeffs_table_two_out1[27] = 27'sb111110111001111110011010101;
  assign coeffs_table_two_out1[28] = 27'sb111110101111101100100111110;
  assign coeffs_table_two_out1[29] = 27'sb111110100100000110110010010;
  assign coeffs_table_two_out1[30] = 27'sb111110010111000010000001000;
  assign coeffs_table_two_out1[31] = 27'sb111110001000010001101110001;
  assign coeffs_table_two_out1[32] = 27'sb111100110111100011011111011;
  assign coeffs_table_two_out1[33] = 27'sb111100111000011000011101011;
  assign coeffs_table_two_out1[34] = 27'sb111100111001001101100011000;
  assign coeffs_table_two_out1[35] = 27'sb111100111010000010101110010;
  assign coeffs_table_two_out1[36] = 27'sb111100111010110111111101001;
  assign coeffs_table_two_out1[37] = 27'sb111100111011101101001101111;
  assign coeffs_table_two_out1[38] = 27'sb111100111100100010011111000;
  assign coeffs_table_two_out1[39] = 27'sb111100111101010111101111000;
  assign coeffs_table_two_out1[40] = 27'sb111100111110001100111100010;
  assign coeffs_table_two_out1[41] = 27'sb111100111111000010000101110;
  assign coeffs_table_two_out1[42] = 27'sb111100111111110111001010000;
  assign coeffs_table_two_out1[43] = 27'sb111101000000101100001000000;
  assign coeffs_table_two_out1[44] = 27'sb111101000001100000111110110;
  assign coeffs_table_two_out1[45] = 27'sb111101000010010101101101010;
  assign coeffs_table_two_out1[46] = 27'sb111101000011001010010010100;
  assign coeffs_table_two_out1[47] = 27'sb111101000011111110101101110;
  assign coeffs_table_two_out1[48] = 27'sb111101000100110010111110001;
  assign coeffs_table_two_out1[49] = 27'sb111101000101100111000011000;
  assign coeffs_table_two_out1[50] = 27'sb111101000110011010111011110;
  assign coeffs_table_two_out1[51] = 27'sb111101000111001110100111101;
  assign coeffs_table_two_out1[52] = 27'sb111101001000000010000110001;
  assign coeffs_table_two_out1[53] = 27'sb111101001000110101010110110;
  assign coeffs_table_two_out1[54] = 27'sb111101001001101000011000111;
  assign coeffs_table_two_out1[55] = 27'sb111101001010011011001100010;
  assign coeffs_table_two_out1[56] = 27'sb111101001011001101110000011;
  assign coeffs_table_two_out1[57] = 27'sb111101001100000000000100111;
  assign coeffs_table_two_out1[58] = 27'sb111101001100110010001001011;
  assign coeffs_table_two_out1[59] = 27'sb111101001101100011111101110;
  assign coeffs_table_two_out1[60] = 27'sb111101001110010101100001100;
  assign coeffs_table_two_out1[61] = 27'sb111101001111000110110100011;
  assign coeffs_table_two_out1[62] = 27'sb111101001111110111110110010;
  assign coeffs_table_two_out1[63] = 27'sb111101010000101000100111000;

  assign sqrt_coeffs_table_domain_2_1_out1 = (DTC5_out1 == 8'b00000000 ? coeffs_table_two_out1[0] :
              (DTC5_out1 == 8'b00000001 ? coeffs_table_two_out1[1] :
              (DTC5_out1 == 8'b00000010 ? coeffs_table_two_out1[2] :
              (DTC5_out1 == 8'b00000011 ? coeffs_table_two_out1[3] :
              (DTC5_out1 == 8'b00000100 ? coeffs_table_two_out1[4] :
              (DTC5_out1 == 8'b00000101 ? coeffs_table_two_out1[5] :
              (DTC5_out1 == 8'b00000110 ? coeffs_table_two_out1[6] :
              (DTC5_out1 == 8'b00000111 ? coeffs_table_two_out1[7] :
              (DTC5_out1 == 8'b00001000 ? coeffs_table_two_out1[8] :
              (DTC5_out1 == 8'b00001001 ? coeffs_table_two_out1[9] :
              (DTC5_out1 == 8'b00001010 ? coeffs_table_two_out1[10] :
              (DTC5_out1 == 8'b00001011 ? coeffs_table_two_out1[11] :
              (DTC5_out1 == 8'b00001100 ? coeffs_table_two_out1[12] :
              (DTC5_out1 == 8'b00001101 ? coeffs_table_two_out1[13] :
              (DTC5_out1 == 8'b00001110 ? coeffs_table_two_out1[14] :
              (DTC5_out1 == 8'b00001111 ? coeffs_table_two_out1[15] :
              (DTC5_out1 == 8'b00010000 ? coeffs_table_two_out1[16] :
              (DTC5_out1 == 8'b00010001 ? coeffs_table_two_out1[17] :
              (DTC5_out1 == 8'b00010010 ? coeffs_table_two_out1[18] :
              (DTC5_out1 == 8'b00010011 ? coeffs_table_two_out1[19] :
              (DTC5_out1 == 8'b00010100 ? coeffs_table_two_out1[20] :
              (DTC5_out1 == 8'b00010101 ? coeffs_table_two_out1[21] :
              (DTC5_out1 == 8'b00010110 ? coeffs_table_two_out1[22] :
              (DTC5_out1 == 8'b00010111 ? coeffs_table_two_out1[23] :
              (DTC5_out1 == 8'b00011000 ? coeffs_table_two_out1[24] :
              (DTC5_out1 == 8'b00011001 ? coeffs_table_two_out1[25] :
              (DTC5_out1 == 8'b00011010 ? coeffs_table_two_out1[26] :
              (DTC5_out1 == 8'b00011011 ? coeffs_table_two_out1[27] :
              (DTC5_out1 == 8'b00011100 ? coeffs_table_two_out1[28] :
              (DTC5_out1 == 8'b00011101 ? coeffs_table_two_out1[29] :
              (DTC5_out1 == 8'b00011110 ? coeffs_table_two_out1[30] :
              (DTC5_out1 == 8'b00011111 ? coeffs_table_two_out1[31] :
              (DTC5_out1 == 8'b00100000 ? coeffs_table_two_out1[32] :
              (DTC5_out1 == 8'b00100001 ? coeffs_table_two_out1[33] :
              (DTC5_out1 == 8'b00100010 ? coeffs_table_two_out1[34] :
              (DTC5_out1 == 8'b00100011 ? coeffs_table_two_out1[35] :
              (DTC5_out1 == 8'b00100100 ? coeffs_table_two_out1[36] :
              (DTC5_out1 == 8'b00100101 ? coeffs_table_two_out1[37] :
              (DTC5_out1 == 8'b00100110 ? coeffs_table_two_out1[38] :
              (DTC5_out1 == 8'b00100111 ? coeffs_table_two_out1[39] :
              (DTC5_out1 == 8'b00101000 ? coeffs_table_two_out1[40] :
              (DTC5_out1 == 8'b00101001 ? coeffs_table_two_out1[41] :
              (DTC5_out1 == 8'b00101010 ? coeffs_table_two_out1[42] :
              (DTC5_out1 == 8'b00101011 ? coeffs_table_two_out1[43] :
              (DTC5_out1 == 8'b00101100 ? coeffs_table_two_out1[44] :
              (DTC5_out1 == 8'b00101101 ? coeffs_table_two_out1[45] :
              (DTC5_out1 == 8'b00101110 ? coeffs_table_two_out1[46] :
              (DTC5_out1 == 8'b00101111 ? coeffs_table_two_out1[47] :
              (DTC5_out1 == 8'b00110000 ? coeffs_table_two_out1[48] :
              (DTC5_out1 == 8'b00110001 ? coeffs_table_two_out1[49] :
              (DTC5_out1 == 8'b00110010 ? coeffs_table_two_out1[50] :
              (DTC5_out1 == 8'b00110011 ? coeffs_table_two_out1[51] :
              (DTC5_out1 == 8'b00110100 ? coeffs_table_two_out1[52] :
              (DTC5_out1 == 8'b00110101 ? coeffs_table_two_out1[53] :
              (DTC5_out1 == 8'b00110110 ? coeffs_table_two_out1[54] :
              (DTC5_out1 == 8'b00110111 ? coeffs_table_two_out1[55] :
              (DTC5_out1 == 8'b00111000 ? coeffs_table_two_out1[56] :
              (DTC5_out1 == 8'b00111001 ? coeffs_table_two_out1[57] :
              (DTC5_out1 == 8'b00111010 ? coeffs_table_two_out1[58] :
              (DTC5_out1 == 8'b00111011 ? coeffs_table_two_out1[59] :
              (DTC5_out1 == 8'b00111100 ? coeffs_table_two_out1[60] :
              (DTC5_out1 == 8'b00111101 ? coeffs_table_two_out1[61] :
              (DTC5_out1 == 8'b00111110 ? coeffs_table_two_out1[62] :
              coeffs_table_two_out1[63])))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));

  assign DTC4_out1 = {2'b0, BitSlice_out1};

  assign coeffs_table_three_out1[0] = 27'sb000010101010101100110101111;
  assign coeffs_table_three_out1[1] = 27'sb000010101010111011010000011;
  assign coeffs_table_three_out1[2] = 27'sb000010101011011000001001100;
  assign coeffs_table_three_out1[3] = 27'sb000010101100000011101001011;
  assign coeffs_table_three_out1[4] = 27'sb000010101100111101111100000;
  assign coeffs_table_three_out1[5] = 27'sb000010101110000111010010001;
  assign coeffs_table_three_out1[6] = 27'sb000010101111100000000000100;
  assign coeffs_table_three_out1[7] = 27'sb000010110001001000100000111;
  assign coeffs_table_three_out1[8] = 27'sb000010110011000001010001011;
  assign coeffs_table_three_out1[9] = 27'sb000010110101001010110101110;
  assign coeffs_table_three_out1[10] = 27'sb000010110111100101110110111;
  assign coeffs_table_three_out1[11] = 27'sb000010111010010011000100000;
  assign coeffs_table_three_out1[12] = 27'sb000010111101010011010010100;
  assign coeffs_table_three_out1[13] = 27'sb000011000000100111011110110;
  assign coeffs_table_three_out1[14] = 27'sb000011000100010000101101000;
  assign coeffs_table_three_out1[15] = 27'sb000011001000010000001001101;
  assign coeffs_table_three_out1[16] = 27'sb000011001100100111001010101;
  assign coeffs_table_three_out1[17] = 27'sb000011010001010111010000001;
  assign coeffs_table_three_out1[18] = 27'sb000011010110100010000101110;
  assign coeffs_table_three_out1[19] = 27'sb000011011100001001100100010;
  assign coeffs_table_three_out1[20] = 27'sb000011100010001111110010101;
  assign coeffs_table_three_out1[21] = 27'sb000011101000110111001000011;
  assign coeffs_table_three_out1[22] = 27'sb000011110000000010001111011;
  assign coeffs_table_three_out1[23] = 27'sb000011110111110100000110011;
  assign coeffs_table_three_out1[24] = 27'sb000100000000010000000100100;
  assign coeffs_table_three_out1[25] = 27'sb000100001001011001111100000;
  assign coeffs_table_three_out1[26] = 27'sb000100010011010101111110101;
  assign coeffs_table_three_out1[27] = 27'sb000100011110001001000010100;
  assign coeffs_table_three_out1[28] = 27'sb000100101001111000101000001;
  assign coeffs_table_three_out1[29] = 27'sb000100110110101011000000111;
  assign coeffs_table_three_out1[30] = 27'sb000101000100100111010111100;
  assign coeffs_table_three_out1[31] = 27'sb000101010011110101111001111;
  assign coeffs_table_three_out1[32] = 27'sb000000101100110001000101010;
  assign coeffs_table_three_out1[33] = 27'sb000000101011111101101101101;
  assign coeffs_table_three_out1[34] = 27'sb000000101011001011101111110;
  assign coeffs_table_three_out1[35] = 27'sb000000101010011011001000001;
  assign coeffs_table_three_out1[36] = 27'sb000000101001101011110011101;
  assign coeffs_table_three_out1[37] = 27'sb000000101000111101101111010;
  assign coeffs_table_three_out1[38] = 27'sb000000101000010000111000010;
  assign coeffs_table_three_out1[39] = 27'sb000000100111100101001011111;
  assign coeffs_table_three_out1[40] = 27'sb000000100110111010100111011;
  assign coeffs_table_three_out1[41] = 27'sb000000100110010001001000100;
  assign coeffs_table_three_out1[42] = 27'sb000000100101101000101100110;
  assign coeffs_table_three_out1[43] = 27'sb000000100101000001010001110;
  assign coeffs_table_three_out1[44] = 27'sb000000100100011010110101100;
  assign coeffs_table_three_out1[45] = 27'sb000000100011110101010101110;
  assign coeffs_table_three_out1[46] = 27'sb000000100011010000110000101;
  assign coeffs_table_three_out1[47] = 27'sb000000100010101101000100001;
  assign coeffs_table_three_out1[48] = 27'sb000000100010001010001110100;
  assign coeffs_table_three_out1[49] = 27'sb000000100001101000001101110;
  assign coeffs_table_three_out1[50] = 27'sb000000100001000111000000100;
  assign coeffs_table_three_out1[51] = 27'sb000000100000100110100100111;
  assign coeffs_table_three_out1[52] = 27'sb000000100000000110111001011;
  assign coeffs_table_three_out1[53] = 27'sb000000011111100111111100101;
  assign coeffs_table_three_out1[54] = 27'sb000000011111001001101101000;
  assign coeffs_table_three_out1[55] = 27'sb000000011110101100001001010;
  assign coeffs_table_three_out1[56] = 27'sb000000011110001111010000000;
  assign coeffs_table_three_out1[57] = 27'sb000000011101110011000000000;
  assign coeffs_table_three_out1[58] = 27'sb000000011101010111010111111;
  assign coeffs_table_three_out1[59] = 27'sb000000011100111100010110101;
  assign coeffs_table_three_out1[60] = 27'sb000000011100100001111010111;
  assign coeffs_table_three_out1[61] = 27'sb000000011100001000000011111;
  assign coeffs_table_three_out1[62] = 27'sb000000011011101110110000010;
  assign coeffs_table_three_out1[63] = 27'sb000000011011010101111111000;

  assign sqrt_coeffs_table_domain_3_out1 = (DTC4_out1 == 8'b00000000 ? coeffs_table_three_out1[0] :
              (DTC4_out1 == 8'b00000001 ? coeffs_table_three_out1[1] :
              (DTC4_out1 == 8'b00000010 ? coeffs_table_three_out1[2] :
              (DTC4_out1 == 8'b00000011 ? coeffs_table_three_out1[3] :
              (DTC4_out1 == 8'b00000100 ? coeffs_table_three_out1[4] :
              (DTC4_out1 == 8'b00000101 ? coeffs_table_three_out1[5] :
              (DTC4_out1 == 8'b00000110 ? coeffs_table_three_out1[6] :
              (DTC4_out1 == 8'b00000111 ? coeffs_table_three_out1[7] :
              (DTC4_out1 == 8'b00001000 ? coeffs_table_three_out1[8] :
              (DTC4_out1 == 8'b00001001 ? coeffs_table_three_out1[9] :
              (DTC4_out1 == 8'b00001010 ? coeffs_table_three_out1[10] :
              (DTC4_out1 == 8'b00001011 ? coeffs_table_three_out1[11] :
              (DTC4_out1 == 8'b00001100 ? coeffs_table_three_out1[12] :
              (DTC4_out1 == 8'b00001101 ? coeffs_table_three_out1[13] :
              (DTC4_out1 == 8'b00001110 ? coeffs_table_three_out1[14] :
              (DTC4_out1 == 8'b00001111 ? coeffs_table_three_out1[15] :
              (DTC4_out1 == 8'b00010000 ? coeffs_table_three_out1[16] :
              (DTC4_out1 == 8'b00010001 ? coeffs_table_three_out1[17] :
              (DTC4_out1 == 8'b00010010 ? coeffs_table_three_out1[18] :
              (DTC4_out1 == 8'b00010011 ? coeffs_table_three_out1[19] :
              (DTC4_out1 == 8'b00010100 ? coeffs_table_three_out1[20] :
              (DTC4_out1 == 8'b00010101 ? coeffs_table_three_out1[21] :
              (DTC4_out1 == 8'b00010110 ? coeffs_table_three_out1[22] :
              (DTC4_out1 == 8'b00010111 ? coeffs_table_three_out1[23] :
              (DTC4_out1 == 8'b00011000 ? coeffs_table_three_out1[24] :
              (DTC4_out1 == 8'b00011001 ? coeffs_table_three_out1[25] :
              (DTC4_out1 == 8'b00011010 ? coeffs_table_three_out1[26] :
              (DTC4_out1 == 8'b00011011 ? coeffs_table_three_out1[27] :
              (DTC4_out1 == 8'b00011100 ? coeffs_table_three_out1[28] :
              (DTC4_out1 == 8'b00011101 ? coeffs_table_three_out1[29] :
              (DTC4_out1 == 8'b00011110 ? coeffs_table_three_out1[30] :
              (DTC4_out1 == 8'b00011111 ? coeffs_table_three_out1[31] :
              (DTC4_out1 == 8'b00100000 ? coeffs_table_three_out1[32] :
              (DTC4_out1 == 8'b00100001 ? coeffs_table_three_out1[33] :
              (DTC4_out1 == 8'b00100010 ? coeffs_table_three_out1[34] :
              (DTC4_out1 == 8'b00100011 ? coeffs_table_three_out1[35] :
              (DTC4_out1 == 8'b00100100 ? coeffs_table_three_out1[36] :
              (DTC4_out1 == 8'b00100101 ? coeffs_table_three_out1[37] :
              (DTC4_out1 == 8'b00100110 ? coeffs_table_three_out1[38] :
              (DTC4_out1 == 8'b00100111 ? coeffs_table_three_out1[39] :
              (DTC4_out1 == 8'b00101000 ? coeffs_table_three_out1[40] :
              (DTC4_out1 == 8'b00101001 ? coeffs_table_three_out1[41] :
              (DTC4_out1 == 8'b00101010 ? coeffs_table_three_out1[42] :
              (DTC4_out1 == 8'b00101011 ? coeffs_table_three_out1[43] :
              (DTC4_out1 == 8'b00101100 ? coeffs_table_three_out1[44] :
              (DTC4_out1 == 8'b00101101 ? coeffs_table_three_out1[45] :
              (DTC4_out1 == 8'b00101110 ? coeffs_table_three_out1[46] :
              (DTC4_out1 == 8'b00101111 ? coeffs_table_three_out1[47] :
              (DTC4_out1 == 8'b00110000 ? coeffs_table_three_out1[48] :
              (DTC4_out1 == 8'b00110001 ? coeffs_table_three_out1[49] :
              (DTC4_out1 == 8'b00110010 ? coeffs_table_three_out1[50] :
              (DTC4_out1 == 8'b00110011 ? coeffs_table_three_out1[51] :
              (DTC4_out1 == 8'b00110100 ? coeffs_table_three_out1[52] :
              (DTC4_out1 == 8'b00110101 ? coeffs_table_three_out1[53] :
              (DTC4_out1 == 8'b00110110 ? coeffs_table_three_out1[54] :
              (DTC4_out1 == 8'b00110111 ? coeffs_table_three_out1[55] :
              (DTC4_out1 == 8'b00111000 ? coeffs_table_three_out1[56] :
              (DTC4_out1 == 8'b00111001 ? coeffs_table_three_out1[57] :
              (DTC4_out1 == 8'b00111010 ? coeffs_table_three_out1[58] :
              (DTC4_out1 == 8'b00111011 ? coeffs_table_three_out1[59] :
              (DTC4_out1 == 8'b00111100 ? coeffs_table_three_out1[60] :
              (DTC4_out1 == 8'b00111101 ? coeffs_table_three_out1[61] :
              (DTC4_out1 == 8'b00111110 ? coeffs_table_three_out1[62] :
              coeffs_table_three_out1[63])))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));

  assign DTC3_out1 = {1'b0, if_exp_0_1_out1[35:10]};

  assign res_x_mul_temp = sqrt_coeffs_table_domain_3_out1 * DTC3_out1;
  assign res_x_out1 = res_x_mul_temp[51:25];

  assign res_x_coeffs_3_1_add_cast = {{5{sqrt_coeffs_table_domain_2_1_out1[26]}}, sqrt_coeffs_table_domain_2_1_out1};
  assign res_x_coeffs_3_1_add_cast_1 = {{5{res_x_out1[26]}}, res_x_out1};
  assign res_x_coeffs_3_1_add_temp = res_x_coeffs_3_1_add_cast + res_x_coeffs_3_1_add_cast_1;
  assign res_x_coeffs_3_1_out1 = res_x_coeffs_3_1_add_temp[26:0];

  assign DTC2_out1 = {2'b0, BitSlice_out1};

  assign res_x_mul_temp_1 = res_x_coeffs_3_1_out1 * DTC3_out1;
  assign res_x_out1_1 = res_x_mul_temp_1[51:25];

  assign coeffs_table_one_out1[0] = 27'sb010000000000000000000000000;
  assign coeffs_table_one_out1[1] = 27'sb010000000000000000000000010;
  assign coeffs_table_one_out1[2] = 27'sb010000000000000000000010001;
  assign coeffs_table_one_out1[3] = 27'sb010000000000000000001000011;
  assign coeffs_table_one_out1[4] = 27'sb010000000000000000010111001;
  assign coeffs_table_one_out1[5] = 27'sb010000000000000000110100000;
  assign coeffs_table_one_out1[6] = 27'sb010000000000000001100110001;
  assign coeffs_table_one_out1[7] = 27'sb010000000000000010110110100;
  assign coeffs_table_one_out1[8] = 27'sb010000000000000100101111101;
  assign coeffs_table_one_out1[9] = 27'sb010000000000000111011110001;
  assign coeffs_table_one_out1[10] = 27'sb010000000000001011010000111;
  assign coeffs_table_one_out1[11] = 27'sb010000000000010000011000111;
  assign coeffs_table_one_out1[12] = 27'sb010000000000010111001010000;
  assign coeffs_table_one_out1[13] = 27'sb010000000000011111111011000;
  assign coeffs_table_one_out1[14] = 27'sb010000000000101011000110001;
  assign coeffs_table_one_out1[15] = 27'sb010000000000111001001001000;
  assign coeffs_table_one_out1[16] = 27'sb010000000001001010100110001;
  assign coeffs_table_one_out1[17] = 27'sb010000000001100000000100100;
  assign coeffs_table_one_out1[18] = 27'sb010000000001111010010000101;
  assign coeffs_table_one_out1[19] = 27'sb010000000010011001111101111;
  assign coeffs_table_one_out1[20] = 27'sb010000000011000000000110011;
  assign coeffs_table_one_out1[21] = 27'sb010000000011101101101101011;
  assign coeffs_table_one_out1[22] = 27'sb010000000100100011111111100;
  assign coeffs_table_one_out1[23] = 27'sb010000000101100100010101001;
  assign coeffs_table_one_out1[24] = 27'sb010000000110110000010011101;
  assign coeffs_table_one_out1[25] = 27'sb010000001000001001110000000;
  assign coeffs_table_one_out1[26] = 27'sb010000001001110010110001110;
  assign coeffs_table_one_out1[27] = 27'sb010000001011101101110101011;
  assign coeffs_table_one_out1[28] = 27'sb010000001101111101110001000;
  assign coeffs_table_one_out1[29] = 27'sb010000010000100101111000011;
  assign coeffs_table_one_out1[30] = 27'sb010000010011101010000011000;
  assign coeffs_table_one_out1[31] = 27'sb010000010111001110110011001;
  assign coeffs_table_one_out1[32] = 27'sb011001000101100010001111100;
  assign coeffs_table_one_out1[33] = 27'sb011001000101010100100101101;
  assign coeffs_table_one_out1[34] = 27'sb011001000101000110011111001;
  assign coeffs_table_one_out1[35] = 27'sb011001000100110111111100101;
  assign coeffs_table_one_out1[36] = 27'sb011001000100101000111110100;
  assign coeffs_table_one_out1[37] = 27'sb011001000100011001100101001;
  assign coeffs_table_one_out1[38] = 27'sb011001000100001001110001001;
  assign coeffs_table_one_out1[39] = 27'sb011001000011111001100010111;
  assign coeffs_table_one_out1[40] = 27'sb011001000011101000111010110;
  assign coeffs_table_one_out1[41] = 27'sb011001000011010111111001010;
  assign coeffs_table_one_out1[42] = 27'sb011001000011000110011110111;
  assign coeffs_table_one_out1[43] = 27'sb011001000010110100101100000;
  assign coeffs_table_one_out1[44] = 27'sb011001000010100010100001010;
  assign coeffs_table_one_out1[45] = 27'sb011001000010001111111111000;
  assign coeffs_table_one_out1[46] = 27'sb011001000001111101000101101;
  assign coeffs_table_one_out1[47] = 27'sb011001000001101001110101101;
  assign coeffs_table_one_out1[48] = 27'sb011001000001010110001111100;
  assign coeffs_table_one_out1[49] = 27'sb011001000001000010010011110;
  assign coeffs_table_one_out1[50] = 27'sb011001000000101110000010101;
  assign coeffs_table_one_out1[51] = 27'sb011001000000011001011100101;
  assign coeffs_table_one_out1[52] = 27'sb011001000000000100100010010;
  assign coeffs_table_one_out1[53] = 27'sb011000111111101111010100000;
  assign coeffs_table_one_out1[54] = 27'sb011000111111011001110010001;
  assign coeffs_table_one_out1[55] = 27'sb011000111111000011111101000;
  assign coeffs_table_one_out1[56] = 27'sb011000111110101101110101010;
  assign coeffs_table_one_out1[57] = 27'sb011000111110010111011011001;
  assign coeffs_table_one_out1[58] = 27'sb011000111110000000101111001;
  assign coeffs_table_one_out1[59] = 27'sb011000111101101001110001101;
  assign coeffs_table_one_out1[60] = 27'sb011000111101010010100010111;
  assign coeffs_table_one_out1[61] = 27'sb011000111100111011000011011;
  assign coeffs_table_one_out1[62] = 27'sb011000111100100011010011100;
  assign coeffs_table_one_out1[63] = 27'sb011000111100001011010011100;

  assign sqrt_coeffs_table_domain_1_out1 = (DTC2_out1 == 8'b00000000 ? coeffs_table_one_out1[0] :
              (DTC2_out1 == 8'b00000001 ? coeffs_table_one_out1[1] :
              (DTC2_out1 == 8'b00000010 ? coeffs_table_one_out1[2] :
              (DTC2_out1 == 8'b00000011 ? coeffs_table_one_out1[3] :
              (DTC2_out1 == 8'b00000100 ? coeffs_table_one_out1[4] :
              (DTC2_out1 == 8'b00000101 ? coeffs_table_one_out1[5] :
              (DTC2_out1 == 8'b00000110 ? coeffs_table_one_out1[6] :
              (DTC2_out1 == 8'b00000111 ? coeffs_table_one_out1[7] :
              (DTC2_out1 == 8'b00001000 ? coeffs_table_one_out1[8] :
              (DTC2_out1 == 8'b00001001 ? coeffs_table_one_out1[9] :
              (DTC2_out1 == 8'b00001010 ? coeffs_table_one_out1[10] :
              (DTC2_out1 == 8'b00001011 ? coeffs_table_one_out1[11] :
              (DTC2_out1 == 8'b00001100 ? coeffs_table_one_out1[12] :
              (DTC2_out1 == 8'b00001101 ? coeffs_table_one_out1[13] :
              (DTC2_out1 == 8'b00001110 ? coeffs_table_one_out1[14] :
              (DTC2_out1 == 8'b00001111 ? coeffs_table_one_out1[15] :
              (DTC2_out1 == 8'b00010000 ? coeffs_table_one_out1[16] :
              (DTC2_out1 == 8'b00010001 ? coeffs_table_one_out1[17] :
              (DTC2_out1 == 8'b00010010 ? coeffs_table_one_out1[18] :
              (DTC2_out1 == 8'b00010011 ? coeffs_table_one_out1[19] :
              (DTC2_out1 == 8'b00010100 ? coeffs_table_one_out1[20] :
              (DTC2_out1 == 8'b00010101 ? coeffs_table_one_out1[21] :
              (DTC2_out1 == 8'b00010110 ? coeffs_table_one_out1[22] :
              (DTC2_out1 == 8'b00010111 ? coeffs_table_one_out1[23] :
              (DTC2_out1 == 8'b00011000 ? coeffs_table_one_out1[24] :
              (DTC2_out1 == 8'b00011001 ? coeffs_table_one_out1[25] :
              (DTC2_out1 == 8'b00011010 ? coeffs_table_one_out1[26] :
              (DTC2_out1 == 8'b00011011 ? coeffs_table_one_out1[27] :
              (DTC2_out1 == 8'b00011100 ? coeffs_table_one_out1[28] :
              (DTC2_out1 == 8'b00011101 ? coeffs_table_one_out1[29] :
              (DTC2_out1 == 8'b00011110 ? coeffs_table_one_out1[30] :
              (DTC2_out1 == 8'b00011111 ? coeffs_table_one_out1[31] :
              (DTC2_out1 == 8'b00100000 ? coeffs_table_one_out1[32] :
              (DTC2_out1 == 8'b00100001 ? coeffs_table_one_out1[33] :
              (DTC2_out1 == 8'b00100010 ? coeffs_table_one_out1[34] :
              (DTC2_out1 == 8'b00100011 ? coeffs_table_one_out1[35] :
              (DTC2_out1 == 8'b00100100 ? coeffs_table_one_out1[36] :
              (DTC2_out1 == 8'b00100101 ? coeffs_table_one_out1[37] :
              (DTC2_out1 == 8'b00100110 ? coeffs_table_one_out1[38] :
              (DTC2_out1 == 8'b00100111 ? coeffs_table_one_out1[39] :
              (DTC2_out1 == 8'b00101000 ? coeffs_table_one_out1[40] :
              (DTC2_out1 == 8'b00101001 ? coeffs_table_one_out1[41] :
              (DTC2_out1 == 8'b00101010 ? coeffs_table_one_out1[42] :
              (DTC2_out1 == 8'b00101011 ? coeffs_table_one_out1[43] :
              (DTC2_out1 == 8'b00101100 ? coeffs_table_one_out1[44] :
              (DTC2_out1 == 8'b00101101 ? coeffs_table_one_out1[45] :
              (DTC2_out1 == 8'b00101110 ? coeffs_table_one_out1[46] :
              (DTC2_out1 == 8'b00101111 ? coeffs_table_one_out1[47] :
              (DTC2_out1 == 8'b00110000 ? coeffs_table_one_out1[48] :
              (DTC2_out1 == 8'b00110001 ? coeffs_table_one_out1[49] :
              (DTC2_out1 == 8'b00110010 ? coeffs_table_one_out1[50] :
              (DTC2_out1 == 8'b00110011 ? coeffs_table_one_out1[51] :
              (DTC2_out1 == 8'b00110100 ? coeffs_table_one_out1[52] :
              (DTC2_out1 == 8'b00110101 ? coeffs_table_one_out1[53] :
              (DTC2_out1 == 8'b00110110 ? coeffs_table_one_out1[54] :
              (DTC2_out1 == 8'b00110111 ? coeffs_table_one_out1[55] :
              (DTC2_out1 == 8'b00111000 ? coeffs_table_one_out1[56] :
              (DTC2_out1 == 8'b00111001 ? coeffs_table_one_out1[57] :
              (DTC2_out1 == 8'b00111010 ? coeffs_table_one_out1[58] :
              (DTC2_out1 == 8'b00111011 ? coeffs_table_one_out1[59] :
              (DTC2_out1 == 8'b00111100 ? coeffs_table_one_out1[60] :
              (DTC2_out1 == 8'b00111101 ? coeffs_table_one_out1[61] :
              (DTC2_out1 == 8'b00111110 ? coeffs_table_one_out1[62] :
              coeffs_table_one_out1[63])))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));

  assign res_x_coeffs_2_1_add_cast = {{5{res_x_out1_1[26]}}, res_x_out1_1};
  assign res_x_coeffs_2_1_add_cast_1 = {{5{sqrt_coeffs_table_domain_1_out1[26]}}, sqrt_coeffs_table_domain_1_out1};
  assign res_x_coeffs_2_1_add_temp = res_x_coeffs_2_1_add_cast + res_x_coeffs_2_1_add_cast_1;
  assign res_x_coeffs_2_1_out1 = res_x_coeffs_2_1_add_temp[26:0];

  assign Bit_Slice_out1 = res_x_coeffs_2_1_out1;

  assign cmp3_out1 = if_exp_0_1_out1 == 36'h000000000;

  assign cmp0_out1 = if_exp_0_out1 >= 9'sb000000000;

  assign cmp1_out1 = cmp3_out1 | cmp0_out1;

  assign Logical_Operator_out1_1 = cmp1_out1 | Relational_Operator_out1_1;

  assign c1_out1_1 = 36'h800000000;

  assign add1_sub_temp = c1_out1_1 - if_exp_0_1_out1;
  assign add1_out1 = {add1_sub_temp, 1'b0};

  assign Data_Type_Conversion_out1_2 = add1_out1[35:0];

  assign Bit_Slice1_out1 = Data_Type_Conversion_out1_2[1];

  assign Constant45_out1 = 8'sb00100011;

  assign Bit_Slice35_out1 = Data_Type_Conversion_out1_2[2];

  assign Constant1_out1 = 8'sb00100010;

  assign Switch1_out1 = (Bit_Slice1_out1 == 1'b0 ? Constant45_out1 :
              Constant1_out1);

  assign Bit_Slice34_out1 = Data_Type_Conversion_out1_2[3];

  assign Constant44_out1 = 8'sb00100001;

  assign Switch46_out1 = (Bit_Slice35_out1 == 1'b0 ? Switch1_out1 :
              Constant44_out1);

  assign Bit_Slice33_out1 = Data_Type_Conversion_out1_2[4];

  assign Constant43_out1 = 8'sb00100000;

  assign Switch45_out1 = (Bit_Slice34_out1 == 1'b0 ? Switch46_out1 :
              Constant43_out1);

  assign Bit_Slice32_out1 = Data_Type_Conversion_out1_2[5];

  assign Constant42_out1 = 8'sb00011111;

  assign Switch44_out1 = (Bit_Slice33_out1 == 1'b0 ? Switch45_out1 :
              Constant42_out1);

  assign Bit_Slice31_out1 = Data_Type_Conversion_out1_2[6];

  assign Constant41_out1 = 8'sb00011110;

  assign Switch43_out1 = (Bit_Slice32_out1 == 1'b0 ? Switch44_out1 :
              Constant41_out1);

  assign Bit_Slice42_out1 = Data_Type_Conversion_out1_2[7];

  assign Constant39_out1 = 8'sb00011101;

  assign Switch42_out1 = (Bit_Slice31_out1 == 1'b0 ? Switch43_out1 :
              Constant39_out1);

  assign Bit_Slice41_out1 = Data_Type_Conversion_out1_2[8];

  assign Constant38_out1 = 8'sb00011100;

  assign Switch41_out1 = (Bit_Slice42_out1 == 1'b0 ? Switch42_out1 :
              Constant38_out1);

  assign Bit_Slice40_out1 = Data_Type_Conversion_out1_2[9];

  assign Constant37_out1 = 8'sb00011011;

  assign Switch40_out1 = (Bit_Slice41_out1 == 1'b0 ? Switch41_out1 :
              Constant37_out1);

  assign Bit_Slice39_out1 = Data_Type_Conversion_out1_2[10];

  assign Constant36_out1 = 8'sb00011010;

  assign Switch39_out1 = (Bit_Slice40_out1 == 1'b0 ? Switch40_out1 :
              Constant36_out1);

  assign Bit_Slice37_out1 = Data_Type_Conversion_out1_2[11];

  assign Constant35_out1 = 8'sb00011001;

  assign Switch34_out1 = (Bit_Slice39_out1 == 1'b0 ? Switch39_out1 :
              Constant35_out1);

  assign Bit_Slice36_out1 = Data_Type_Conversion_out1_2[12];

  assign Constant34_out1 = 8'sb00011000;

  assign Switch33_out1 = (Bit_Slice37_out1 == 1'b0 ? Switch34_out1 :
              Constant34_out1);

  assign Bit_Slice30_out1 = Data_Type_Conversion_out1_2[13];

  assign Constant33_out1 = 8'sb00010111;

  assign Switch32_out1 = (Bit_Slice36_out1 == 1'b0 ? Switch33_out1 :
              Constant33_out1);

  assign Bit_Slice29_out1 = Data_Type_Conversion_out1_2[14];

  assign Constant32_out1 = 8'sb00010110;

  assign Switch31_out1 = (Bit_Slice30_out1 == 1'b0 ? Switch32_out1 :
              Constant32_out1);

  assign Bit_Slice53_out1 = Data_Type_Conversion_out1_2[15];

  assign Constant31_out1 = 8'sb00010101;

  assign Switch30_out1 = (Bit_Slice29_out1 == 1'b0 ? Switch31_out1 :
              Constant31_out1);

  assign Bit_Slice52_out1 = Data_Type_Conversion_out1_2[16];

  assign Constant30_out1 = 8'sb00010100;

  assign Switch29_out1 = (Bit_Slice53_out1 == 1'b0 ? Switch30_out1 :
              Constant30_out1);

  assign Bit_Slice51_out1 = Data_Type_Conversion_out1_2[17];

  assign Constant55_out1 = 8'sb00010011;

  assign Switch53_out1 = (Bit_Slice52_out1 == 1'b0 ? Switch29_out1 :
              Constant55_out1);

  assign Bit_Slice49_out1 = Data_Type_Conversion_out1_2[18];

  assign Constant54_out1 = 8'sb00010010;

  assign Switch52_out1 = (Bit_Slice51_out1 == 1'b0 ? Switch53_out1 :
              Constant54_out1);

  assign Bit_Slice48_out1 = Data_Type_Conversion_out1_2[19];

  assign Constant53_out1 = 8'sb00010001;

  assign Switch51_out1 = (Bit_Slice49_out1 == 1'b0 ? Switch52_out1 :
              Constant53_out1);

  assign Bit_Slice47_out1 = Data_Type_Conversion_out1_2[20];

  assign Constant52_out1 = 8'sb00010000;

  assign Switch50_out1 = (Bit_Slice48_out1 == 1'b0 ? Switch51_out1 :
              Constant52_out1);

  assign Bit_Slice38_out1 = Data_Type_Conversion_out1_2[21];

  assign Constant51_out1 = 8'sb00001111;

  assign Switch49_out1 = (Bit_Slice47_out1 == 1'b0 ? Switch50_out1 :
              Constant51_out1);

  assign Bit_Slice28_out1 = Data_Type_Conversion_out1_2[22];

  assign Constant50_out1 = 8'sb00001110;

  assign Switch48_out1 = (Bit_Slice38_out1 == 1'b0 ? Switch49_out1 :
              Constant50_out1);

  assign Bit_Slice17_out1 = Data_Type_Conversion_out1_2[23];

  assign Constant49_out1 = 8'sb00001101;

  assign Switch47_out1 = (Bit_Slice28_out1 == 1'b0 ? Switch48_out1 :
              Constant49_out1);

  assign Bit_Slice45_out1 = Data_Type_Conversion_out1_2[24];

  assign Constant40_out1 = 8'sb00001100;

  assign Switch38_out1 = (Bit_Slice17_out1 == 1'b0 ? Switch47_out1 :
              Constant40_out1);

  assign Bit_Slice44_out1 = Data_Type_Conversion_out1_2[25];

  assign Constant29_out1 = 8'sb00001011;

  assign Switch28_out1 = (Bit_Slice45_out1 == 1'b0 ? Switch38_out1 :
              Constant29_out1);

  assign Bit_Slice43_out1 = Data_Type_Conversion_out1_2[26];

  assign Constant27_out1 = 8'sb00001010;

  assign Switch19_out1 = (Bit_Slice44_out1 == 1'b0 ? Switch28_out1 :
              Constant27_out1);

  assign Bit_Slice46_out1 = Data_Type_Conversion_out1_2[27];

  assign Constant56_out1 = 8'sb00001001;

  assign Switch55_out1 = (Bit_Slice43_out1 == 1'b0 ? Switch19_out1 :
              Constant56_out1);

  assign Bit_Slice16_out1 = Data_Type_Conversion_out1_2[28];

  assign Constant28_out1 = 8'sb00001000;

  assign Switch54_out1 = (Bit_Slice46_out1 == 1'b0 ? Switch55_out1 :
              Constant28_out1);

  assign Bit_Slice15_out1 = Data_Type_Conversion_out1_2[29];

  assign Constant26_out1 = 8'sb00000111;

  assign Switch18_out1 = (Bit_Slice16_out1 == 1'b0 ? Switch54_out1 :
              Constant26_out1);

  assign Bit_Slice14_out1 = Data_Type_Conversion_out1_2[30];

  assign Constant25_out1 = 8'sb00000110;

  assign Switch17_out1 = (Bit_Slice15_out1 == 1'b0 ? Switch18_out1 :
              Constant25_out1);

  assign Bit_Slice13_out1 = Data_Type_Conversion_out1_2[31];

  assign Constant24_out1 = 8'sb00000101;

  assign Switch16_out1 = (Bit_Slice14_out1 == 1'b0 ? Switch17_out1 :
              Constant24_out1);

  assign Bit_Slice12_out1 = Data_Type_Conversion_out1_2[32];

  assign Constant23_out1 = 8'sb00000100;

  assign Switch27_out1 = (Bit_Slice13_out1 == 1'b0 ? Switch16_out1 :
              Constant23_out1);

  assign Bit_Slice23_out1 = Data_Type_Conversion_out1_2[33];

  assign Constant22_out1 = 8'sb00000011;

  assign Switch26_out1 = (Bit_Slice12_out1 == 1'b0 ? Switch27_out1 :
              Constant22_out1);

  assign Bit_Slice22_out1 = Data_Type_Conversion_out1_2[34];

  assign Constant21_out1 = 8'sb00000010;

  assign Switch25_out1 = (Bit_Slice23_out1 == 1'b0 ? Switch26_out1 :
              Constant21_out1);

  assign Bit_Slice21_out1 = Data_Type_Conversion_out1_2[35];

  assign Constant20_out1 = 8'sb00000001;

  assign Switch24_out1 = (Bit_Slice22_out1 == 1'b0 ? Switch25_out1 :
              Constant20_out1);

  assign Constant19_out1 = 8'sb00000000;

  assign Switch23_out1 = (Bit_Slice21_out1 == 1'b0 ? Switch24_out1 :
              Constant19_out1);

  assign Unary_Minus_1 = {Switch23_out1[7], Switch23_out1};
  assign Unary_Minus_in0 =  - (Unary_Minus_1);
  assign Unary_Minus_out1 = Unary_Minus_in0[7:0];

  assign BitSlice3_out1 = Unary_Minus_out1[0];

  assign bitsliceget_s_e_1_2_out1 = BitSlice3_out1 == 1'b1;

  assign BitClear_out1 = Unary_Minus_out1 & 8'sb11111110;

  assign s1_out1 = (bitsliceget_s_e_1_2_out1 == 1'b0 ? Unary_Minus_out1 :
              BitClear_out1);

  assign cmp1_out1_1 = s1_out1 < 8'sb00000000;

  assign Data_Type_Conversion2_out1 = Switch23_out1[5:0];

  assign dynamic_shift_2 = {2'b0, Data_Type_Conversion2_out1};
  assign Shift_Arithmetic_out1 = Data_Type_Conversion_out1_2 <<< dynamic_shift_2;

  assign Data_Type_Conversion1_out1 = Shift_Arithmetic_out1;

  assign DTC_out1_1 = Data_Type_Conversion1_out1[35:9];

  assign BitSlice_out1_1 = DTC_out1_1[25:21];

  assign DTC2_out1_1 = {3'b0, BitSlice_out1_1};

  assign sqrt_coeffs_table_out1[0] = 27'sb110100111100100000001001011;
  assign sqrt_coeffs_table_out1[1] = 27'sb110101011011111100101000011;
  assign sqrt_coeffs_table_out1[2] = 27'sb110101111001001000010101000;
  assign sqrt_coeffs_table_out1[3] = 27'sb110110010100010001011010100;
  assign sqrt_coeffs_table_out1[4] = 27'sb110110101101100100010100111;
  assign sqrt_coeffs_table_out1[5] = 27'sb110111000101001100000001100;
  assign sqrt_coeffs_table_out1[6] = 27'sb110111011011010010001100001;
  assign sqrt_coeffs_table_out1[7] = 27'sb110111101111111111011010011;
  assign sqrt_coeffs_table_out1[8] = 27'sb111000000011011011010101010;
  assign sqrt_coeffs_table_out1[9] = 27'sb111000010101101100110000111;
  assign sqrt_coeffs_table_out1[10] = 27'sb111000100110111001110011100;
  assign sqrt_coeffs_table_out1[11] = 27'sb111000110111000111111011011;
  assign sqrt_coeffs_table_out1[12] = 27'sb111001000110011100000011100;
  assign sqrt_coeffs_table_out1[13] = 27'sb111001010100111010100111111;
  assign sqrt_coeffs_table_out1[14] = 27'sb111001100010100111101001000;
  assign sqrt_coeffs_table_out1[15] = 27'sb111001101111100110101111011;
  assign sqrt_coeffs_table_out1[16] = 27'sb111001111011111011001110000;
  assign sqrt_coeffs_table_out1[17] = 27'sb111010000111101000000100110;
  assign sqrt_coeffs_table_out1[18] = 27'sb111010010010110000000010100;
  assign sqrt_coeffs_table_out1[19] = 27'sb111010011101010101100111000;
  assign sqrt_coeffs_table_out1[20] = 27'sb111010100111011011000100011;
  assign sqrt_coeffs_table_out1[21] = 27'sb111010110001000010100000010;
  assign sqrt_coeffs_table_out1[22] = 27'sb111010111010001101110101101;
  assign sqrt_coeffs_table_out1[23] = 27'sb111011000010111110110101011;
  assign sqrt_coeffs_table_out1[24] = 27'sb111011001011010111000111011;
  assign sqrt_coeffs_table_out1[25] = 27'sb111011010011011000001011101;
  assign sqrt_coeffs_table_out1[26] = 27'sb111011011011000011011010101;
  assign sqrt_coeffs_table_out1[27] = 27'sb111011100010011010000110000;
  assign sqrt_coeffs_table_out1[28] = 27'sb111011101001011101011001111;
  assign sqrt_coeffs_table_out1[29] = 27'sb111011110000001110011100010;
  assign sqrt_coeffs_table_out1[30] = 27'sb111011110110101110001110100;
  assign sqrt_coeffs_table_out1[31] = 27'sb111011111100111101101101010;

  assign sqrt_coeffs_table_domain_3_out1_1 = (DTC2_out1_1 == 8'b00000000 ? sqrt_coeffs_table_out1[0] :
              (DTC2_out1_1 == 8'b00000001 ? sqrt_coeffs_table_out1[1] :
              (DTC2_out1_1 == 8'b00000010 ? sqrt_coeffs_table_out1[2] :
              (DTC2_out1_1 == 8'b00000011 ? sqrt_coeffs_table_out1[3] :
              (DTC2_out1_1 == 8'b00000100 ? sqrt_coeffs_table_out1[4] :
              (DTC2_out1_1 == 8'b00000101 ? sqrt_coeffs_table_out1[5] :
              (DTC2_out1_1 == 8'b00000110 ? sqrt_coeffs_table_out1[6] :
              (DTC2_out1_1 == 8'b00000111 ? sqrt_coeffs_table_out1[7] :
              (DTC2_out1_1 == 8'b00001000 ? sqrt_coeffs_table_out1[8] :
              (DTC2_out1_1 == 8'b00001001 ? sqrt_coeffs_table_out1[9] :
              (DTC2_out1_1 == 8'b00001010 ? sqrt_coeffs_table_out1[10] :
              (DTC2_out1_1 == 8'b00001011 ? sqrt_coeffs_table_out1[11] :
              (DTC2_out1_1 == 8'b00001100 ? sqrt_coeffs_table_out1[12] :
              (DTC2_out1_1 == 8'b00001101 ? sqrt_coeffs_table_out1[13] :
              (DTC2_out1_1 == 8'b00001110 ? sqrt_coeffs_table_out1[14] :
              (DTC2_out1_1 == 8'b00001111 ? sqrt_coeffs_table_out1[15] :
              (DTC2_out1_1 == 8'b00010000 ? sqrt_coeffs_table_out1[16] :
              (DTC2_out1_1 == 8'b00010001 ? sqrt_coeffs_table_out1[17] :
              (DTC2_out1_1 == 8'b00010010 ? sqrt_coeffs_table_out1[18] :
              (DTC2_out1_1 == 8'b00010011 ? sqrt_coeffs_table_out1[19] :
              (DTC2_out1_1 == 8'b00010100 ? sqrt_coeffs_table_out1[20] :
              (DTC2_out1_1 == 8'b00010101 ? sqrt_coeffs_table_out1[21] :
              (DTC2_out1_1 == 8'b00010110 ? sqrt_coeffs_table_out1[22] :
              (DTC2_out1_1 == 8'b00010111 ? sqrt_coeffs_table_out1[23] :
              (DTC2_out1_1 == 8'b00011000 ? sqrt_coeffs_table_out1[24] :
              (DTC2_out1_1 == 8'b00011001 ? sqrt_coeffs_table_out1[25] :
              (DTC2_out1_1 == 8'b00011010 ? sqrt_coeffs_table_out1[26] :
              (DTC2_out1_1 == 8'b00011011 ? sqrt_coeffs_table_out1[27] :
              (DTC2_out1_1 == 8'b00011100 ? sqrt_coeffs_table_out1[28] :
              (DTC2_out1_1 == 8'b00011101 ? sqrt_coeffs_table_out1[29] :
              (DTC2_out1_1 == 8'b00011110 ? sqrt_coeffs_table_out1[30] :
              sqrt_coeffs_table_out1[31])))))))))))))))))))))))))))))));

  assign DTC7_out1 = {3'b0, BitSlice_out1_1};

  assign res_s_m_cast = {1'b0, DTC_out1_1};
  assign res_s_m_mul_temp = sqrt_coeffs_table_domain_3_out1_1 * res_s_m_cast;
  assign res_s_m_cast_1 = res_s_m_mul_temp[53:0];
  assign res_s_m_out1 = res_s_m_cast_1[53:27];

  assign sqrt_coeffs_table_out1_1[0] = 27'b100001101011100011100101111;
  assign sqrt_coeffs_table_out1_1[1] = 27'b100001001011001000100101101;
  assign sqrt_coeffs_table_out1_1[2] = 27'b100000101100001000011111110;
  assign sqrt_coeffs_table_out1_1[3] = 27'b100000001110011100110111001;
  assign sqrt_coeffs_table_out1_1[4] = 27'b011111110001111111110111000;
  assign sqrt_coeffs_table_out1_1[5] = 27'b011111010110101100001101010;
  assign sqrt_coeffs_table_out1_1[6] = 27'b011110111100011101000111010;
  assign sqrt_coeffs_table_out1_1[7] = 27'b011110100011001110001101001;
  assign sqrt_coeffs_table_out1_1[8] = 27'b011110001010111011011111110;
  assign sqrt_coeffs_table_out1_1[9] = 27'b011101110011100001010101101;
  assign sqrt_coeffs_table_out1_1[10] = 27'b011101011100111100011000010;
  assign sqrt_coeffs_table_out1_1[11] = 27'b011101000111001001100011001;
  assign sqrt_coeffs_table_out1_1[12] = 27'b011100110010000110000000101;
  assign sqrt_coeffs_table_out1_1[13] = 27'b011100011101101111001001101;
  assign sqrt_coeffs_table_out1_1[14] = 27'b011100001010000010100011100;
  assign sqrt_coeffs_table_out1_1[15] = 27'b011011110110111101111111000;
  assign sqrt_coeffs_table_out1_1[16] = 27'b011011100100011111010111100;
  assign sqrt_coeffs_table_out1_1[17] = 27'b011011010010100100110001101;
  assign sqrt_coeffs_table_out1_1[18] = 27'b011011000001001100011010101;
  assign sqrt_coeffs_table_out1_1[19] = 27'b011010110000010100100111101;
  assign sqrt_coeffs_table_out1_1[20] = 27'b011010011111111011110100110;
  assign sqrt_coeffs_table_out1_1[21] = 27'b011010010000000000100101001;
  assign sqrt_coeffs_table_out1_1[22] = 27'b011010000000100001100001010;
  assign sqrt_coeffs_table_out1_1[23] = 27'b011001110001011101010111110;
  assign sqrt_coeffs_table_out1_1[24] = 27'b011001100010110010111011111;
  assign sqrt_coeffs_table_out1_1[25] = 27'b011001010100100001000101111;
  assign sqrt_coeffs_table_out1_1[26] = 27'b011001000110100110110010001;
  assign sqrt_coeffs_table_out1_1[27] = 27'b011000111001000011000001001;
  assign sqrt_coeffs_table_out1_1[28] = 27'b011000101011110100110110111;
  assign sqrt_coeffs_table_out1_1[29] = 27'b011000011110111011011011001;
  assign sqrt_coeffs_table_out1_1[30] = 27'b011000010010010101111000011;
  assign sqrt_coeffs_table_out1_1[31] = 27'b011000000110000011011100011;

  assign sqrt_coeffs_table_domain_2_out1 = (DTC7_out1 == 8'b00000000 ? sqrt_coeffs_table_out1_1[0] :
              (DTC7_out1 == 8'b00000001 ? sqrt_coeffs_table_out1_1[1] :
              (DTC7_out1 == 8'b00000010 ? sqrt_coeffs_table_out1_1[2] :
              (DTC7_out1 == 8'b00000011 ? sqrt_coeffs_table_out1_1[3] :
              (DTC7_out1 == 8'b00000100 ? sqrt_coeffs_table_out1_1[4] :
              (DTC7_out1 == 8'b00000101 ? sqrt_coeffs_table_out1_1[5] :
              (DTC7_out1 == 8'b00000110 ? sqrt_coeffs_table_out1_1[6] :
              (DTC7_out1 == 8'b00000111 ? sqrt_coeffs_table_out1_1[7] :
              (DTC7_out1 == 8'b00001000 ? sqrt_coeffs_table_out1_1[8] :
              (DTC7_out1 == 8'b00001001 ? sqrt_coeffs_table_out1_1[9] :
              (DTC7_out1 == 8'b00001010 ? sqrt_coeffs_table_out1_1[10] :
              (DTC7_out1 == 8'b00001011 ? sqrt_coeffs_table_out1_1[11] :
              (DTC7_out1 == 8'b00001100 ? sqrt_coeffs_table_out1_1[12] :
              (DTC7_out1 == 8'b00001101 ? sqrt_coeffs_table_out1_1[13] :
              (DTC7_out1 == 8'b00001110 ? sqrt_coeffs_table_out1_1[14] :
              (DTC7_out1 == 8'b00001111 ? sqrt_coeffs_table_out1_1[15] :
              (DTC7_out1 == 8'b00010000 ? sqrt_coeffs_table_out1_1[16] :
              (DTC7_out1 == 8'b00010001 ? sqrt_coeffs_table_out1_1[17] :
              (DTC7_out1 == 8'b00010010 ? sqrt_coeffs_table_out1_1[18] :
              (DTC7_out1 == 8'b00010011 ? sqrt_coeffs_table_out1_1[19] :
              (DTC7_out1 == 8'b00010100 ? sqrt_coeffs_table_out1_1[20] :
              (DTC7_out1 == 8'b00010101 ? sqrt_coeffs_table_out1_1[21] :
              (DTC7_out1 == 8'b00010110 ? sqrt_coeffs_table_out1_1[22] :
              (DTC7_out1 == 8'b00010111 ? sqrt_coeffs_table_out1_1[23] :
              (DTC7_out1 == 8'b00011000 ? sqrt_coeffs_table_out1_1[24] :
              (DTC7_out1 == 8'b00011001 ? sqrt_coeffs_table_out1_1[25] :
              (DTC7_out1 == 8'b00011010 ? sqrt_coeffs_table_out1_1[26] :
              (DTC7_out1 == 8'b00011011 ? sqrt_coeffs_table_out1_1[27] :
              (DTC7_out1 == 8'b00011100 ? sqrt_coeffs_table_out1_1[28] :
              (DTC7_out1 == 8'b00011101 ? sqrt_coeffs_table_out1_1[29] :
              (DTC7_out1 == 8'b00011110 ? sqrt_coeffs_table_out1_1[30] :
              sqrt_coeffs_table_out1_1[31])))))))))))))))))))))))))))))));

  assign res_s_m_coeffs_two_add_cast = {{5{res_s_m_out1[26]}}, res_s_m_out1};
  assign res_s_m_coeffs_two_add_cast_1 = {5'b0, sqrt_coeffs_table_domain_2_out1};
  assign res_s_m_coeffs_two_add_temp = res_s_m_coeffs_two_add_cast + res_s_m_coeffs_two_add_cast_1;
  assign res_s_m_coeffs_two_out1 = res_s_m_coeffs_two_add_temp[26:0];

  assign DTC5_out1_1 = res_s_m_coeffs_two_out1;

  assign DTC1_out1_1 = {3'b0, BitSlice_out1_1};

  assign res_s_m_mul_temp_1 = DTC5_out1_1 * DTC_out1_1;
  assign res_s_m_out1_1 = res_s_m_mul_temp_1[53:27];

  assign sqrt_coeffs_table_out1_2[0] = 27'sb001000100011010000000100101;
  assign sqrt_coeffs_table_out1_2[1] = 27'sb001000101011100110111100110;
  assign sqrt_coeffs_table_out1_2[2] = 27'sb001000110011110101111001010;
  assign sqrt_coeffs_table_out1_2[3] = 27'sb001000111011111101010000001;
  assign sqrt_coeffs_table_out1_2[4] = 27'sb001001000011111101010101110;
  assign sqrt_coeffs_table_out1_2[5] = 27'sb001001001011110110011101001;
  assign sqrt_coeffs_table_out1_2[6] = 27'sb001001010011101000111000001;
  assign sqrt_coeffs_table_out1_2[7] = 27'sb001001011011010100110111001;
  assign sqrt_coeffs_table_out1_2[8] = 27'sb001001100010111010101010000;
  assign sqrt_coeffs_table_out1_2[9] = 27'sb001001101010011010011111000;
  assign sqrt_coeffs_table_out1_2[10] = 27'sb001001110001110100100100001;
  assign sqrt_coeffs_table_out1_2[11] = 27'sb001001111001001001000110010;
  assign sqrt_coeffs_table_out1_2[12] = 27'sb001010000000011000010001011;
  assign sqrt_coeffs_table_out1_2[13] = 27'sb001010000111100010010001001;
  assign sqrt_coeffs_table_out1_2[14] = 27'sb001010001110100111010000100;
  assign sqrt_coeffs_table_out1_2[15] = 27'sb001010010101100111011001101;
  assign sqrt_coeffs_table_out1_2[16] = 27'sb001010011100100010110110010;
  assign sqrt_coeffs_table_out1_2[17] = 27'sb001010100011011001101111110;
  assign sqrt_coeffs_table_out1_2[18] = 27'sb001010101010001100001110110;
  assign sqrt_coeffs_table_out1_2[19] = 27'sb001010110000111010011011110;
  assign sqrt_coeffs_table_out1_2[20] = 27'sb001010110111100100011110101;
  assign sqrt_coeffs_table_out1_2[21] = 27'sb001010111110001010011111000;
  assign sqrt_coeffs_table_out1_2[22] = 27'sb001011000100101100100100000;
  assign sqrt_coeffs_table_out1_2[23] = 27'sb001011001011001010110100100;
  assign sqrt_coeffs_table_out1_2[24] = 27'sb001011010001100101010111010;
  assign sqrt_coeffs_table_out1_2[25] = 27'sb001011010111111100010010011;
  assign sqrt_coeffs_table_out1_2[26] = 27'sb001011011110001111101100000;
  assign sqrt_coeffs_table_out1_2[27] = 27'sb001011100100011111101001111;
  assign sqrt_coeffs_table_out1_2[28] = 27'sb001011101010101100010001011;
  assign sqrt_coeffs_table_out1_2[29] = 27'sb001011110000110101101000000;
  assign sqrt_coeffs_table_out1_2[30] = 27'sb001011110110111011110010101;
  assign sqrt_coeffs_table_out1_2[31] = 27'sb001011111100111110110110011;

  assign sqrt_coeffs_table_domain_1_out1_1 = (DTC1_out1_1 == 8'b00000000 ? sqrt_coeffs_table_out1_2[0] :
              (DTC1_out1_1 == 8'b00000001 ? sqrt_coeffs_table_out1_2[1] :
              (DTC1_out1_1 == 8'b00000010 ? sqrt_coeffs_table_out1_2[2] :
              (DTC1_out1_1 == 8'b00000011 ? sqrt_coeffs_table_out1_2[3] :
              (DTC1_out1_1 == 8'b00000100 ? sqrt_coeffs_table_out1_2[4] :
              (DTC1_out1_1 == 8'b00000101 ? sqrt_coeffs_table_out1_2[5] :
              (DTC1_out1_1 == 8'b00000110 ? sqrt_coeffs_table_out1_2[6] :
              (DTC1_out1_1 == 8'b00000111 ? sqrt_coeffs_table_out1_2[7] :
              (DTC1_out1_1 == 8'b00001000 ? sqrt_coeffs_table_out1_2[8] :
              (DTC1_out1_1 == 8'b00001001 ? sqrt_coeffs_table_out1_2[9] :
              (DTC1_out1_1 == 8'b00001010 ? sqrt_coeffs_table_out1_2[10] :
              (DTC1_out1_1 == 8'b00001011 ? sqrt_coeffs_table_out1_2[11] :
              (DTC1_out1_1 == 8'b00001100 ? sqrt_coeffs_table_out1_2[12] :
              (DTC1_out1_1 == 8'b00001101 ? sqrt_coeffs_table_out1_2[13] :
              (DTC1_out1_1 == 8'b00001110 ? sqrt_coeffs_table_out1_2[14] :
              (DTC1_out1_1 == 8'b00001111 ? sqrt_coeffs_table_out1_2[15] :
              (DTC1_out1_1 == 8'b00010000 ? sqrt_coeffs_table_out1_2[16] :
              (DTC1_out1_1 == 8'b00010001 ? sqrt_coeffs_table_out1_2[17] :
              (DTC1_out1_1 == 8'b00010010 ? sqrt_coeffs_table_out1_2[18] :
              (DTC1_out1_1 == 8'b00010011 ? sqrt_coeffs_table_out1_2[19] :
              (DTC1_out1_1 == 8'b00010100 ? sqrt_coeffs_table_out1_2[20] :
              (DTC1_out1_1 == 8'b00010101 ? sqrt_coeffs_table_out1_2[21] :
              (DTC1_out1_1 == 8'b00010110 ? sqrt_coeffs_table_out1_2[22] :
              (DTC1_out1_1 == 8'b00010111 ? sqrt_coeffs_table_out1_2[23] :
              (DTC1_out1_1 == 8'b00011000 ? sqrt_coeffs_table_out1_2[24] :
              (DTC1_out1_1 == 8'b00011001 ? sqrt_coeffs_table_out1_2[25] :
              (DTC1_out1_1 == 8'b00011010 ? sqrt_coeffs_table_out1_2[26] :
              (DTC1_out1_1 == 8'b00011011 ? sqrt_coeffs_table_out1_2[27] :
              (DTC1_out1_1 == 8'b00011100 ? sqrt_coeffs_table_out1_2[28] :
              (DTC1_out1_1 == 8'b00011101 ? sqrt_coeffs_table_out1_2[29] :
              (DTC1_out1_1 == 8'b00011110 ? sqrt_coeffs_table_out1_2[30] :
              sqrt_coeffs_table_out1_2[31])))))))))))))))))))))))))))))));

  assign DTC6_out1 = {sqrt_coeffs_table_domain_1_out1_1[25:0], 1'b0};

  assign res_s_m_coeffs_one_add_cast = {4'b0, {res_s_m_out1_1, 1'b0}};
  assign res_s_m_coeffs_one_add_cast_1 = {5'b0, DTC6_out1};
  assign res_s_m_coeffs_one_add_temp = res_s_m_coeffs_one_add_cast + res_s_m_coeffs_one_add_cast_1;
  assign res_s_m_coeffs_one_out1 = res_s_m_coeffs_one_add_temp[27:1];

  assign c2_out1 = 27'b101101010000010011110011010;

  assign mul1_mul_temp = c2_out1 * res_s_m_coeffs_one_out1;
  assign mul1_out1 = mul1_mul_temp[52:26];

  assign s3_out1 = (bitsliceget_s_e_1_2_out1 == 1'b0 ? res_s_m_coeffs_one_out1 :
              mul1_out1);

  assign dtc3_out1_1 = {s3_out1, 9'b000000000};

  assign bitsra_s_e_1_out1 = s1_out1 >>> 8'd1;

  assign alphas_e_1 = {bitsra_s_e_1_out1[7], bitsra_s_e_1_out1};
  assign alphas_e_in0 =  - (alphas_e_1);
  assign alphas_e_out1 = alphas_e_in0[7:0];

  assign dtc4_out1_1 = alphas_e_out1[5:0];

  assign dynamic_shift_cast_1 = {2'b0, dtc4_out1_1};
  assign bitsra_y_s_e_out1 = dtc3_out1_1 >>> dynamic_shift_cast_1;

  assign s2_out1_1 = (cmp1_out1_1 == 1'b0 ? dtc3_out1_1 :
              bitsra_y_s_e_out1);

  assign compare_out1 = (Logical_Operator_out1_1 == 1'b0 ? s2_out1_1 :
              if_exp_0_1_out1);

  assign Bit_Slice2_out1 = compare_out1[26:0];

  assign Bit_Slice1_out1_1 = compare_out1[35:27];

  assign z0_out1 = Bit_Slice_out1 * Bit_Slice2_out1;

  assign z1_out1 = Bit_Slice_out1 * Bit_Slice1_out1_1;

  assign Data_Type_Conversion_out1_3 = {28'b0, z1_out1};

  assign Bit_Shift_out1 = Data_Type_Conversion_out1_3 <<< 8'd27;

  assign Sum_1 = {10'b0, z0_out1};
  assign Sum_out1 = Sum_1 + Bit_Shift_out1;

  assign Data_Type_Conversion4_out1 = Sum_out1;

  assign Data_Type_Conversion3_out1 = Data_Type_Conversion4_out1[60:25];

  assign C2_out1_1 = 36'hC90FDAA22;

  assign Add_out1 = C2_out1_1 - Data_Type_Conversion3_out1;

  assign compare1_out1 = (Logical_Operator1_out1 == 1'b0 ? Data_Type_Conversion3_out1 :
              Add_out1);

  assign compare3_out1 = (compare2_out1 == 1'b0 ? compare1_out1 :
              C2_out1_1);

  assign cmp0_out1_1 = compare3_out1 == 36'h000000000;

  assign alpha127_out1_1 = 8'b01111111;

  assign Data_Type_Conversion1_out1_1 = {1'b0, compare3_out1[35:1]};

  assign Data_Type_Conversion_out1_4 = Data_Type_Conversion1_out1_1;

  assign Bit_Slice35_out1_1 = Data_Type_Conversion_out1_4[1];

  assign Constant45_out1_1 = 8'sb00100010;

  assign Bit_Slice34_out1_1 = Data_Type_Conversion_out1_4[2];

  assign Constant44_out1_1 = 8'sb00100001;

  assign Switch46_out1_1 = (Bit_Slice35_out1_1 == 1'b0 ? Constant45_out1_1 :
              Constant44_out1_1);

  assign Bit_Slice33_out1_1 = Data_Type_Conversion_out1_4[3];

  assign Constant43_out1_1 = 8'sb00100000;

  assign Switch45_out1_1 = (Bit_Slice34_out1_1 == 1'b0 ? Switch46_out1_1 :
              Constant43_out1_1);

  assign Bit_Slice32_out1_1 = Data_Type_Conversion_out1_4[4];

  assign Constant42_out1_1 = 8'sb00011111;

  assign Switch44_out1_1 = (Bit_Slice33_out1_1 == 1'b0 ? Switch45_out1_1 :
              Constant42_out1_1);

  assign Bit_Slice31_out1_1 = Data_Type_Conversion_out1_4[5];

  assign Constant41_out1_1 = 8'sb00011110;

  assign Switch43_out1_1 = (Bit_Slice32_out1_1 == 1'b0 ? Switch44_out1_1 :
              Constant41_out1_1);

  assign Bit_Slice42_out1_1 = Data_Type_Conversion_out1_4[6];

  assign Constant39_out1_1 = 8'sb00011101;

  assign Switch42_out1_1 = (Bit_Slice31_out1_1 == 1'b0 ? Switch43_out1_1 :
              Constant39_out1_1);

  assign Bit_Slice41_out1_1 = Data_Type_Conversion_out1_4[7];

  assign Constant38_out1_1 = 8'sb00011100;

  assign Switch41_out1_1 = (Bit_Slice42_out1_1 == 1'b0 ? Switch42_out1_1 :
              Constant38_out1_1);

  assign Bit_Slice40_out1_1 = Data_Type_Conversion_out1_4[8];

  assign Constant37_out1_1 = 8'sb00011011;

  assign Switch40_out1_1 = (Bit_Slice41_out1_1 == 1'b0 ? Switch41_out1_1 :
              Constant37_out1_1);

  assign Bit_Slice39_out1_1 = Data_Type_Conversion_out1_4[9];

  assign Constant36_out1_1 = 8'sb00011010;

  assign Switch39_out1_1 = (Bit_Slice40_out1_1 == 1'b0 ? Switch40_out1_1 :
              Constant36_out1_1);

  assign Bit_Slice37_out1_1 = Data_Type_Conversion_out1_4[10];

  assign Constant35_out1_1 = 8'sb00011001;

  assign Switch34_out1_1 = (Bit_Slice39_out1_1 == 1'b0 ? Switch39_out1_1 :
              Constant35_out1_1);

  assign Bit_Slice36_out1_1 = Data_Type_Conversion_out1_4[11];

  assign Constant34_out1_1 = 8'sb00011000;

  assign Switch33_out1_1 = (Bit_Slice37_out1_1 == 1'b0 ? Switch34_out1_1 :
              Constant34_out1_1);

  assign Bit_Slice30_out1_1 = Data_Type_Conversion_out1_4[12];

  assign Constant33_out1_1 = 8'sb00010111;

  assign Switch32_out1_1 = (Bit_Slice36_out1_1 == 1'b0 ? Switch33_out1_1 :
              Constant33_out1_1);

  assign Bit_Slice29_out1_1 = Data_Type_Conversion_out1_4[13];

  assign Constant32_out1_1 = 8'sb00010110;

  assign Switch31_out1_1 = (Bit_Slice30_out1_1 == 1'b0 ? Switch32_out1_1 :
              Constant32_out1_1);

  assign Bit_Slice53_out1_1 = Data_Type_Conversion_out1_4[14];

  assign Constant31_out1_1 = 8'sb00010101;

  assign Switch30_out1_1 = (Bit_Slice29_out1_1 == 1'b0 ? Switch31_out1_1 :
              Constant31_out1_1);

  assign Bit_Slice52_out1_1 = Data_Type_Conversion_out1_4[15];

  assign Constant30_out1_1 = 8'sb00010100;

  assign Switch29_out1_1 = (Bit_Slice53_out1_1 == 1'b0 ? Switch30_out1_1 :
              Constant30_out1_1);

  assign Bit_Slice51_out1_1 = Data_Type_Conversion_out1_4[16];

  assign Constant55_out1_1 = 8'sb00010011;

  assign Switch53_out1_1 = (Bit_Slice52_out1_1 == 1'b0 ? Switch29_out1_1 :
              Constant55_out1_1);

  assign Bit_Slice49_out1_1 = Data_Type_Conversion_out1_4[17];

  assign Constant54_out1_1 = 8'sb00010010;

  assign Switch52_out1_1 = (Bit_Slice51_out1_1 == 1'b0 ? Switch53_out1_1 :
              Constant54_out1_1);

  assign Bit_Slice48_out1_1 = Data_Type_Conversion_out1_4[18];

  assign Constant53_out1_1 = 8'sb00010001;

  assign Switch51_out1_1 = (Bit_Slice49_out1_1 == 1'b0 ? Switch52_out1_1 :
              Constant53_out1_1);

  assign Bit_Slice47_out1_1 = Data_Type_Conversion_out1_4[19];

  assign Constant52_out1_1 = 8'sb00010000;

  assign Switch50_out1_1 = (Bit_Slice48_out1_1 == 1'b0 ? Switch51_out1_1 :
              Constant52_out1_1);

  assign Bit_Slice38_out1_1 = Data_Type_Conversion_out1_4[20];

  assign Constant51_out1_1 = 8'sb00001111;

  assign Switch49_out1_1 = (Bit_Slice47_out1_1 == 1'b0 ? Switch50_out1_1 :
              Constant51_out1_1);

  assign Bit_Slice28_out1_1 = Data_Type_Conversion_out1_4[21];

  assign Constant50_out1_1 = 8'sb00001110;

  assign Switch48_out1_1 = (Bit_Slice38_out1_1 == 1'b0 ? Switch49_out1_1 :
              Constant50_out1_1);

  assign Bit_Slice17_out1_1 = Data_Type_Conversion_out1_4[22];

  assign Constant49_out1_1 = 8'sb00001101;

  assign Switch47_out1_1 = (Bit_Slice28_out1_1 == 1'b0 ? Switch48_out1_1 :
              Constant49_out1_1);

  assign Bit_Slice45_out1_1 = Data_Type_Conversion_out1_4[23];

  assign Constant40_out1_1 = 8'sb00001100;

  assign Switch38_out1_1 = (Bit_Slice17_out1_1 == 1'b0 ? Switch47_out1_1 :
              Constant40_out1_1);

  assign Bit_Slice44_out1_1 = Data_Type_Conversion_out1_4[24];

  assign Constant29_out1_1 = 8'sb00001011;

  assign Switch28_out1_1 = (Bit_Slice45_out1_1 == 1'b0 ? Switch38_out1_1 :
              Constant29_out1_1);

  assign Bit_Slice43_out1_1 = Data_Type_Conversion_out1_4[25];

  assign Constant27_out1_1 = 8'sb00001010;

  assign Switch19_out1_1 = (Bit_Slice44_out1_1 == 1'b0 ? Switch28_out1_1 :
              Constant27_out1_1);

  assign Bit_Slice46_out1_1 = Data_Type_Conversion_out1_4[26];

  assign Constant56_out1_1 = 8'sb00001001;

  assign Switch55_out1_1 = (Bit_Slice43_out1_1 == 1'b0 ? Switch19_out1_1 :
              Constant56_out1_1);

  assign Bit_Slice16_out1_1 = Data_Type_Conversion_out1_4[27];

  assign Constant28_out1_1 = 8'sb00001000;

  assign Switch54_out1_1 = (Bit_Slice46_out1_1 == 1'b0 ? Switch55_out1_1 :
              Constant28_out1_1);

  assign Bit_Slice15_out1_1 = Data_Type_Conversion_out1_4[28];

  assign Constant26_out1_1 = 8'sb00000111;

  assign Switch18_out1_1 = (Bit_Slice16_out1_1 == 1'b0 ? Switch54_out1_1 :
              Constant26_out1_1);

  assign Bit_Slice14_out1_1 = Data_Type_Conversion_out1_4[29];

  assign Constant25_out1_1 = 8'sb00000110;

  assign Switch17_out1_1 = (Bit_Slice15_out1_1 == 1'b0 ? Switch18_out1_1 :
              Constant25_out1_1);

  assign Bit_Slice13_out1_1 = Data_Type_Conversion_out1_4[30];

  assign Constant24_out1_1 = 8'sb00000101;

  assign Switch16_out1_1 = (Bit_Slice14_out1_1 == 1'b0 ? Switch17_out1_1 :
              Constant24_out1_1);

  assign Bit_Slice12_out1_1 = Data_Type_Conversion_out1_4[31];

  assign Constant23_out1_1 = 8'sb00000100;

  assign Switch27_out1_1 = (Bit_Slice13_out1_1 == 1'b0 ? Switch16_out1_1 :
              Constant23_out1_1);

  assign Bit_Slice23_out1_1 = Data_Type_Conversion_out1_4[32];

  assign Constant22_out1_1 = 8'sb00000011;

  assign Switch26_out1_1 = (Bit_Slice12_out1_1 == 1'b0 ? Switch27_out1_1 :
              Constant22_out1_1);

  assign Bit_Slice22_out1_1 = Data_Type_Conversion_out1_4[33];

  assign Constant21_out1_1 = 8'sb00000010;

  assign Switch25_out1_1 = (Bit_Slice23_out1_1 == 1'b0 ? Switch26_out1_1 :
              Constant21_out1_1);

  assign Bit_Slice21_out1_1 = Data_Type_Conversion_out1_4[34];

  assign Constant20_out1_1 = 8'sb00000001;

  assign Switch24_out1_1 = (Bit_Slice22_out1_1 == 1'b0 ? Switch25_out1_1 :
              Constant20_out1_1);

  assign Bit_Slice20_out1 = Data_Type_Conversion_out1_4[35];

  assign Constant19_out1_1 = 8'sb00000000;

  assign Switch23_out1_1 = (Bit_Slice21_out1_1 == 1'b0 ? Switch24_out1_1 :
              Constant19_out1_1);

  assign Constant18_out1 = 8'sb11111111;

  assign Switch22_out1 = (Bit_Slice20_out1 == 1'b0 ? Switch23_out1_1 :
              Constant18_out1);

  assign Sum_3 = {24'b0, alpha127_out1_1};
  assign Sum_4 = {{24{Switch22_out1[7]}}, Switch22_out1};
  assign Sum_sub_temp = Sum_3 - Sum_4;
  assign Sum_out1_1 = Sum_sub_temp[7:0];

  assign E0_out1 = 8'b00000000;

  assign s5_out1 = (cmp0_out1_1 == 1'b0 ? Sum_out1_1 :
              E0_out1);

  assign PipelinePath_out1_dtc = E;

  assign s0_out1 = (Relational_Operator_out1 == 1'b0 ? s5_out1 :
              PipelinePath_out1_dtc);

  assign E1_out1 = 8'b11111111;

  assign s4_out1 = (Logical_Operator_out1 == 1'b0 ? s0_out1 :
              E1_out1);

  assign Switch1_out1_1 = (Constant8_out1 == 1'b0 ? Constant_out1 :
              s4_out1);

  assign Constant1_out1_1 = 23'b00000000000000000000000;

  assign switch_compare_1 = Switch22_out1 >= 8'sb00000000;

  assign Bit_Shift_out1_1 = Data_Type_Conversion_out1_4 >>> 8'd1;

  assign Data_Type_Conversion2_out1_1 = Switch22_out1[5:0];

  assign dynamic_shift_5 = {2'b0, Data_Type_Conversion2_out1_1};
  assign Shift_Arithmetic_out1_1 = Data_Type_Conversion_out1_4 <<< dynamic_shift_5;

  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Bit_Shift_out1_1 :
              Shift_Arithmetic_out1_1);

  assign Bit_Slice1_out1_2 = Switch_out1[33:11];

  assign M0_out1 = 23'b00000000000000000000000;

  assign s6_out1 = (cmp0_out1_1 == 1'b0 ? Bit_Slice1_out1_2 :
              M0_out1);

  assign s1_out1_1 = (Relational_Operator_out1 == 1'b0 ? s6_out1 :
              M);

  assign Bit_Set_out1 = s1_out1_1 | 23'b10000000000000000000000;

  assign s2_out1_2 = (Logical_Operator_out1 == 1'b0 ? s1_out1_1 :
              Bit_Set_out1);

  assign Switch_out1_1 = (Constant8_out1 == 1'b0 ? Constant1_out1_1 :
              s2_out1_2);

  // Combine FP sign, exponent, mantissa into 32 bit word
  assign nfp_out_pack = {S, Switch1_out1_1, Switch_out1_1};

  assign nfp_out = nfp_out_pack;

endmodule  // nfp_asin_single

